### ISSUE TITLE
Feature request: include a Likert Scale

### ISSUE THREAD

**Issue by PedlRio** [JhumanJ/OpnForm#102]
First of all, this is a fantastic open source tool. I've been hunting for this for a while. So, thanks for that.
My suggestion is to include a Likert scale as a feature or improvement to the pick option.

I'm not sure if this is currently possible. So, sorry if it is.

**Comment by JhumanJ** [comment]
Hey, thanks for your kind words.
How would it look like?
How would the data look like?
Any ideas?
Thanks

**Comment by JhumanJ** [comment]
This link maybe can help?
https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error

**Comment by PedlRio** [comment]
A scale of this type is available in the Microsoft Forms.
This option is essentially a grid with rows and columns. The image below serves as an example:

![image](https://user-images.githubusercontent.com/3899146/225308268-cfd0090a-49e3-4d27-8f54-d920dd13ce1d.png)

**Comment by JhumanJ** [comment]
How are the results then presented?

**Comment by PedlRio** [comment]
One way to show it is to cross the row instruction with the column option.
So, for the example below, we could have had this table.

![image](https://user-images.githubusercontent.com/3899146/225412352-c728d78e-ca56-4a10-83fb-e99707344266.png)
![image](https://user-images.githubusercontent.com/3899146/225412365-32fa3b91-b1d5-488b-ac43-2b4db517d084.png)

In this time, I made the Likert scale in Google Forms, because it is more convenient.

**Comment by JhumanJ** [comment]
![CleanShot 2024-08-27 at 10 39 42@2x](https://github.com/user-attachments/assets/aa8935ee-6e3c-4b2a-b77c-01cfaf6f3359)
We've added the new matrix input :)
