### ISSUE TITLE
 The "--f" option does not exist - when running 'make up'

### ISSUE THREAD

**Issue by ainal-3fresources** [JhumanJ/OpnForm#107]
Running **'make up'** stops at this error 

```
INFO  Application key set successfully.

touch .make.artisan-key-generate
docker compose run --rm php-cli artisan jwt:secret --f


  The "--f" option does not exist.


make: *** [Makefile:33: .make.jwt-secret] Error 1
```

I think it is an extra - (dash)
Note: after that I ran 
`docker compose run --rm php-cli artisan jwt:secret -f`
and then 
`docker compose up -d server `
and the container started up and I was able to access OpnForm.

**Comment by JhumanJ** [comment]
Hum that's odd it worked well for me... Any particular setup on your side?

**Comment by mrysn** [comment]
I had to change this to `-f` to get it working.

**Comment by mrysn** [comment]
try changing it to `docker compose run --rm php-cli artisan jwt:secret --force`
