### ISSUE TITLE
Vite manifest not found at: /project/public/build/manifest.json

### ISSUE THREAD

**Issue by ainal-3fresources** [JhumanJ/OpnForm#108]
I am trying to install using docker. I used the 'docker compose up -d server' command. It started a container but when I tried accessing the page, the page gave a Laravel exception : **Vite manifest not found at: /project/public/build/manifest.json** 
in resources / views / spa.blade.php:24

`Exception: Vite manifest not found at: /project/public/build/manifest.json in /project/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:684
Stack trace:
#0 /project/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php(273): Illuminate\Foundation\Vite->manifest('build')
#1 /project/storage/framework/views/b2e4b3f5439b812ed3685a7e4bbc5d909e6f5799.php(24): Illuminate\Foundation\Vite->__invoke(Object(Illuminate\Support\Collection))
#2 /project/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('/project/storag...')
#3 /project/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\Filesystem\Filesystem::Illuminate\Filesystem\{closure}()
#4 /project/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\Filesystem\Filesystem->getRequire('/project/storag...', Array)
#5 /project/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\View\Engines\PhpEngine->evaluatePath('/project/storag...', Array)
#6 /project/vendor/laravel/framework/src/Illuminate/View/View.php(152): Illuminate\View\Engines\CompilerEngine->get('/project/resour...', Array)
#7 /project/vendor/laravel/framework/src/Illuminate/View/View.php(135): Illuminate\View\View->getContents()
#8 /project/vendor/laravel/framework/src/Illuminate/View/View.php(104): Illuminate\View\View->renderContents()
#9 /project/vendor/laravel/framework/src/Illuminate/View/View.php(449): Illuminate\View\View->render()
#10 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(179): Illuminate\View\View->__toString()
#11 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(159): Monolog\Formatter\NormalizerFormatter->normalize(Object(Illuminate\View\View), 5)
#12 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(159): Monolog\Formatter\NormalizerFormatter->normalize(Array, 4)
#13 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(159): Monolog\Formatter\NormalizerFormatter->normalize(Array, 3)
#14 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(159): Monolog\Formatter\NormalizerFormatter->normalize(Array, 2)
#15 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(159): Monolog\Formatter\NormalizerFormatter->normalize(Array, 1)
#16 /project/vendor/monolog/monolog/src/Monolog/Formatter/NormalizerFormatter.php(55): Monolog\Formatter\NormalizerFormatter->normalize(Array)
#17 /project/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php(84): Monolog\Formatter\NormalizerFormatter->format(Array)
#18 /project/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(46): Monolog\Formatter\LineFormatter->format(Array)
#19 /project/vendor/monolog/monolog/src/Monolog/Logger.php(379): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#20 /project/vendor/monolog/monolog/src/Monolog/Logger.php(574): Monolog\Logger->addRecord(100, 'Un-handled Exce...', Array)
#21 /project/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->debug('Un-handled Exce...', Array)
#22 /project/vendor/laravel/framework/src/Illuminate/Log/Logger.php(142): Illuminate\Log\Logger->writeLog('debug', 'Un-handled Exce...', Array)
#23 /project/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(698): Illuminate\Log\Logger->debug('Un-handled Exce...', Array)
#24 /project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Log\LogManager->debug('Un-handled Exce...', Array)
#25 /project/app/Exceptions/Handler.php(63): Illuminate\Support\Facades\Facade::__callStatic('debug', Array)
#26 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(198): App\Exceptions\Handler->report(Object(Illuminate\View\ViewException))
#27 /project/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Illuminate\View\ViewException))
#28 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Illuminate\View\ViewException))
#29 {main}`

**Comment by JhumanJ** [comment]
It seems like you didn't properly start the docker image, and that the front-end has not compiled. Have you tried following the guide with `make`?

**Comment by ainal-3fresources** [comment]
I was trying out the alternative commands. I will try with make. I am building this on a basic Oracle Linux VM with basically make and git installed.

**Comment by ainal-3fresources** [comment]
Running `make up` give this error. 

`<--- Last few GCs --->

[18:0x57b2170]    12413 ms: Mark-sweep 326.2 (343.1) -> 322.2 (343.4) MB, 347.7 / 0.0 ms  (average mu = 0.188, current mu = 0.133) allocation failure scavenge might not succeed
[18:0x57b2170]    12797 ms: Mark-sweep 326.6 (343.6) -> 322.6 (343.9) MB, 344.2 / 0.0 ms  (average mu = 0.147, current mu = 0.104) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb090e0 node::Abort() [node]
 2: 0xa1b70e  [node]
 3: 0xce19d0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce1d77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe993e5  [node]
 6: 0xe99ec6  [node]
 7: 0xea83ee  [node]
 8: 0xea8e30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeabdae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe6d022 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
11: 0xe6793c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
12: 0xe67a15 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
13: 0x10cf78b v8::internal::MaybeHandle<v8::internal::OrderedHashSet> v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
14: 0x10853a8 v8::internal::KeyAccumulator::AddKey(v8::internal::Handle<v8::internal::Object>, v8::internal::AddKeyConversion) [node]
15: 0x10857be  [node]
16: 0x108a2a8 v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [node]
17: 0x108a5bf v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [node]
18: 0x108a853 v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [node]
19: 0x108b263 v8::internal::KeyAccumulator::GetKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::KeyCollectionMode, v8::internal::PropertyFilter, v8::internal::GetKeysConversion, bool, bool) [node]
20: 0x10721ec v8::internal::JSReceiver::DefineProperties(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
21: 0x11ef77e v8::internal::Runtime_ObjectCreate(int, unsigned long*, v8::internal::Isolate*) [node]
22: 0x15d9e19  [node]
Aborted (core dumped)
npm notice
npm notice New major version of npm available! 8.19.4 -> 9.6.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.3
npm notice Run npm install -g npm@9.6.3 to update!
npm notice
make: *** [Makefile:25: .make.npm-build] Error 134
`

Should I upgrade to npm 9.6.3 like it suggests at the end?

**Comment by ainal-3fresources** [comment]
I am using a small VM on KVM with a single CPU and 2GB RAM and running Oracle Linux 8.7 with kernel 5.4.17-2136.317.5.3.el8uek.x86_64 and make-4.2.1-11.el8.x86_64. 
Please let me know if you want to know the versions of other components

**Comment by ainal-3fresources** [comment]
Sorry, forgot to add that it is a minimal install.  Oracle Linux does some things differently in their packages which are not mainstream or core. ie optional repositories.

**Comment by JhumanJ** [comment]
Closing in favor of https://github.com/JhumanJ/OpnForm/issues/146
