### ISSUE TITLE
Color change doesn't work on text blocks

### ISSUE THREAD

**Issue by terryMarsault** [JhumanJ/OpnForm#126]
Hi @JhumanJ, when I apply a color to a text block (H1, H2 titles or simple paragraphs), the color gets back to black as soon I as save my form.

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/bd1410da-464d-409a-b755-afeb3a2d8d3a)
___

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/93be0519-e177-4c06-8265-88c948c60752)

___

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/4afccd90-ee64-49fe-9d4e-56f0bbc3cdfb)

___

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/568f9023-8b39-4105-93ff-f85ebe880c4e)

___

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/5df90146-0f01-4a8b-baca-c9d6d6c10d74)

**Comment by JhumanJ** [comment]
Fixed
