### ISSUE TITLE
From and To labels in a date field with range option

### ISSUE THREAD

**Issue by terryMarsault** [JhumanJ/OpnForm#127]
Hi @JhumanJ, it seems that we can't change the 'From' and 'To' labels in a date field which has the 'Date range' option:

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/1116b4d5-9069-4502-b6da-2257b43bf79d)

**Comment by JhumanJ** [comment]
We don't have translation files for the small details of the UI, but we'd accept a PR for that.
