### ISSUE TITLE
'Upload file' label in a upload field

### ISSUE THREAD

**Issue by terryMarsault** [JhumanJ/OpnForm#129]
Hi, there's no way to change the 'Upload file' text in a upload file input. I would like to translate it in french.

![image](https://github.com/JhumanJ/OpnForm/assets/132718573/3ce692d1-687b-4f34-8e62-ac3a16f124cd)

**Comment by JhumanJ** [comment]
Closing this in favor of https://github.com/JhumanJ/OpnForm/issues/129
