### ISSUE TITLE
Group Form elements in containers with headers.

### ISSUE THREAD

**Issue by d3ra1l** [JhumanJ/OpnForm#143]
I would love to see the ability to hide/show/require grouped form elements. Could even show a section header.

Also, will there being any conditional logic with form submissions?

**Comment by JhumanJ** [comment]
Thanks for the feedback and great idea. What do you mean exactly by conditional logic for form submissions?

**Comment by d3ra1l** [comment]
You can different webhooks and select which webhook to use based on a form value.

**Comment by JhumanJ** [comment]
Hey @robmoredev, you can already do this by adding a page break after each input
