### ISSUE TITLE
service "migrate" didn't complete successfully: exit 255

### ISSUE THREAD

**Issue by akamalmra** [JhumanJ/OpnForm#148]
### Error in Docker
[+] Running 3/3
 ✔ Container opnform-database-1  Healthy                                                                                                                                        5.8s 
 ✔ Container opnform-migrate-1   Exited                                                                                                                                         6.6s 
 ✔ Container opnform-server-1    Created                                                                                                                                        0.0s 
**_service "migrate" didn't complete successfully: exit 255_**

### Error in Browser

`Warning: require(/project/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /project/public/index.php on line 34

Fatal error: Uncaught Error: Failed opening required '/project/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /project/public/index.php:34 Stack trace: #0 {main} thrown in /project/public/index.php on line 34`

**Comment by JhumanJ** [comment]
Fixed in https://github.com/JhumanJ/OpnForm/pull/153
