### ISSUE TITLE
Docker Alternative for production

### ISSUE THREAD

**Issue by aiamk** [JhumanJ/OpnForm#161]
This project looks very promising, good UI and functionality, but unfortunately i see no progress on docker deployment.

can you please provide at least provide manual installation steps for production?

Best Regards

**Comment by JhumanJ** [comment]
Hi, thanks for your interest in the project. We've shipped few days ago a very easy docker image to get started with the project. Please check the readme.

**Comment by aiamk** [comment]
@JhumanJ i did one hour ago, it has many issues, mainly database restarted many times and getting server error 500 in the user interface.

**Comment by JhumanJ** [comment]
Can you please share more info about your errors? Logs, screens etc.

**Comment by aiamk** [comment]
@JhumanJ i will test it again now and log everything

**Comment by aiamk** [comment]
laravel log
[laravel.log](https://github.com/JhumanJ/OpnForm/files/12216488/laravel.log)
