### ISSUE TITLE
Feature Request: Calculations

### ISSUE THREAD

**Issue by karpadiem** [JhumanJ/OpnForm#169]
Posted this in discussions but didn't know if it was better here. :)

### Discussed in https://github.com/JhumanJ/OpnForm/discussions/144

<div type='discussions-op-text'>

<sup>Originally posted by **karpadiem** July  6, 2023</sup>
Really excited about OpnForm. Seems to pretty much fill the void we are trying to fill for forms. One feature we are missing is some sort of calculation based on options selected.

Is this something we could add ourselves using javascript and the custom code field for a form? If so, is there any documentation you could point us in the direction of?</div>

**Comment by ayntk-ai** [comment]
Add a numeric value to each field and then calculate the value based on the answers in the fields (works very well with radio and checkbox fields) calculate the value in a hidden calculation field and then based on the result perform post-submit actions --> This would be a great thing if it could be implemented.

**Comment by JhumanJ** [comment]
Closing in favor of: https://opnform.featurebase.app/p/computed-fields
