### ISSUE TITLE
Phone Input Component

### ISSUE THREAD

**Issue by JhumanJ** [JhumanJ/OpnForm#170]
Currently the input component used for the `phone` type is a basic `<text-input>`. We want to have a dedicated component for the phone type. Ex:
![image](https://github.com/JhumanJ/OpnForm/assets/11312432/321fac0e-c78d-4593-b644-14a99c9c2ff7)

The goal of this issue is to create this `PhoneInput.vue` component, and to use it for the `phone` type. Required data for the countries can be placed as a json in `resources/data`.

**Requirements**
- It should work with all countries and contain nice flags
- It must work will existing form themes (see `form-theme.js`). Themes can be changed in the customization section of the form editor
- The component must be lazy-loaded to avoid loading all of its data on every page. Ex here: [/resources/js/components/forms/index.js#L41](https://github.com/JhumanJ/OpnForm/blob/96ef9d7c25fade952740eff47c4d469be07b810b/resources/js/components/forms/index.js#L41)
- The dropdown must be using our `VSelect.vue` component
- It should handle clashes for instance, for French number you don't need `+33` and start with a `0`, so if user selects `+33` for France, and enters `0123456789`, the resulting value should not be `+330123456789` but `+330123456789`
- It should have a dedicated phone validation rule in the back-end in `AnswerFormRequest`. The number must start with a valid country code and have the right length

Please feel free to reach out if you have any question!

**Comment by Ashutosh-Bhadauriya** [comment]
@JhumanJ I would like to take this 🙂
/attempt #170

**Comment by rishi-raj-jain** [comment]
I'm next in line!

**Comment by sagar-kashyap** [comment]
> the resulting value should not be `+330123456789` but `+330123456789`

@JhumanJ can you clarify your 2nd last point in requirement.

**Comment by JhumanJ** [comment]
Hey guys. So essentially remove the leading 0 if there is one before pre-pending the country code

**Comment by Ashutosh-Bhadauriya** [comment]
Hey @JhumanJ I'm getting this error, when running npm run dev, any idea. I tried googling found some fixes but it didn't help. Also tried adding this to vite.config.js, but no success
`  server: {
    https: true,
    host: 'localhost'
  },`

![image](https://github.com/JhumanJ/OpnForm/assets/62984427/10ca3ceb-aa72-4665-9fb9-e660792ed3ca)

**Comment by JhumanJ** [comment]
Hey @Ashutosh-Bhadauriya, I've just pushed something to fix this, please pull an try again.

**Comment by Ashutosh-Bhadauriya** [comment]
Sure, thanks!

**Comment by Ashutosh-Bhadauriya** [comment]
@rishi-raj-jain I've cancelled my attempt on this, you can take it.

**Comment by rishi-raj-jain** [comment]
@Ashutosh-Bhadauriya I think @ayusham001 is already on it.

**Comment by JhumanJ** [comment]
Hey @ayusham001 can you please confirm or cancel attemp?

**Comment by ayusham001** [comment]
@JhumanJ 
I did the few changes 
But rn m cancelling the attempt

**Comment by Ahtritus** [comment]
Hey, is this still open? If yes, I'd like to have a shot at it

**Comment by JhumanJ** [comment]
Hey. Yes it is. No one is actively working on it. Thank you

Julien Nahum

**Comment by Ahtritus** [comment]
Alright then, I'm taking this.
/attempt #170

**Comment by abhinandanmishra1** [comment]
Hii @JhumanJ ,

Can I also work on this issue? I just want to make a try and it's my open source attempt.

**Comment by Ahtritus** [comment]
@JhumanJ did you guys have any existing plan on how to render the flags? I had initially thought of using the flag emojis like `🇦🇫` for Afghanistan but Chrome isn't properly rendering them, atleast on my side. I could use SVGs for each but it would be a bit more complicated and might bloat the code a little.

**Comment by JhumanJ** [comment]
Good question. Maybe we could use this library: https://github.com/ubaldop/vue-country-flag and lazy load the component? So that flags would only be loaded if the Phone input is loading somewhere on the page. Happy to hear more suggestions.

**Comment by Ahtritus** [comment]
I actually got this beautiful little library called [vue-tel-input](https://github.com/iamstevendao/vue-tel-input) which does all the heavy lifting, don't even require the country-list json. However, the dropdown needs to be styled a but more. Shall try to get a PR up by tomorrow.

<img width="434" alt="image" src="https://github.com/JhumanJ/OpnForm/assets/53258966/e6373933-6fb8-4000-82c9-02c3a1742e73">

**Comment by JhumanJ** [comment]
Hey, it could work but please make sure that the end result work with all of 3 form themes!

Julien Nahum

**Comment by Ahtritus** [comment]
Its a bit trickier than I initially thought. The styles are more or less working with the 3 themes but the borders are acting up a bit. Apart from that, when I try to actually submit the form, its throwing a 500 error with "undefined variable $null" though the request payload has all the values. Might take some more time.

**Comment by JhumanJ** [comment]
Hey @Ahtritus I think you need to do something here to claim the bounty!

**Comment by Ahtritus** [comment]
> Hey @Ahtritus I think you need to do something here to claim the bounty!

lol yeah, i forgot to claim it. Lemme do that in the PR

**Comment by Ahtritus** [comment]
Not sure what's the next step, I guess you have to close it so that I receive the bounty.

**Comment by JhumanJ** [comment]
Let's try!

**Comment by JhumanJ** [comment]
Paid aout, thank you @Ahtritus !

**Comment by Ahtritus** [comment]
Nice working with you man, thanks @JhumanJ !
