### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by JhumanJ** [JhumanJ/OpnForm#171]
This project was developed with PostgreSQL. Many people would like to make it compatible with MySQL. This task is about making the required changes so that it can also work with MySQL.

[See this previous issue about MySQL support](https://github.com/JhumanJ/OpnForm/issues/52)

**Comment by rishi-raj-jain** [comment]
As @evonloch has forfeited their attempt, I'd like to get this.

/attempt #171

**Comment by rishi-raj-jain** [comment]
@evonloch 

Can you help me with the command that'll help me see the MySql Errors?

```
docker run --name opnform -v $PWD/my-opnform-data:/persist -p 80:80 jhumanj/opnform
```

runs just as fine

**Comment by rishi-raj-jain** [comment]
Basically, asking for a reproduction that I can test in my device.

**Comment by JhumanJ** [comment]
Hey @rishi-raj-jain, the docker setup comes with a PostgreSQL database so you won't be able to reproduce it with the docker setup. You need to manually install the project (with valet, or MAMP or equivalent)

**Comment by rishi-raj-jain** [comment]
@JhumanJ 

Can you help me by suggesting which method to use on macOS?

/attempt #171

**Comment by JhumanJ** [comment]
Hey @rishi-raj-jain, I recommend using https://laravel.com/docs/9.x/valet#main-content, the official laravel development environment for Laravel. It should be easy to install with brew. You can then follow [readme explanations](https://github.com/JhumanJ/OpnForm#using-laravel-valet). You of course need mysql, and to change the `.env` variable to use MySQL instead

**Comment by rishi-raj-jain** [comment]
Hey @JhumanJ,

I set up PHP, MySQL successfully. On my way to install composer.

**Comment by rishi-raj-jain** [comment]
Okay, composer was easy. Testing out!

**Comment by rishi-raj-jain** [comment]
@JhumanJ 

<img width="1183" alt="Screenshot 2023-08-19 at 10 26 47 PM" src="https://github.com/JhumanJ/OpnForm/assets/46300090/ce8674c3-3412-452c-8bee-c11a428323e5">

Okay now npm install errors out with as above

**Comment by rishi-raj-jain** [comment]
I'm on a MacOS Ventura

**Comment by rishi-raj-jain** [comment]
Was able to run with lot of brew installations for png and libpng/

**Comment by talktogauravsingh** [comment]
@JhumanJ, is the issue still open or closed?

**Comment by JhumanJ** [comment]
Hey @talktogauravsingh still available if you're interested! I'll close this one.

**Comment by ayewo** [comment]
@JhumanJ since it's still available can you re-open the issue?

Also, how do you intend to maintain support for MySQL? Will it live in a `mysql`-specific branch?

**Comment by JhumanJ** [comment]
My bad I wanted to close the PR, it's re-opened. No, it should be the same branch for both, code should be compatible with both DB engine

**Comment by ayewo** [comment]
Sounds like you beat yourself to closing the PR, 2 weeks ago :)

You proposed this approach (in the closed PR): https://github.com/JhumanJ/OpnForm/pull/173#issuecomment-1709656741 but I'm curious about what other changes will be needed to make the app work for both Postgres and MySQL?

**Comment by iam-subho** [comment]
this issue is still open or closed???

**Comment by simondotwhite** [comment]
Could this be merged if possible?

**Comment by flikites** [comment]
Merged, and then also some documentation on how to specify the remote MySQL server in the docker container would be great!

**Comment by JhumanJ** [comment]
I'm about to merge it, thank you @nhedger!
@flikites these are just for the Github test pipeline, when creating the local MySql instance. To use a custom remote mySQL server, you just need to [customize the docker .env file](https://github.com/JhumanJ/OpnForm#using-a-custom-env-file) to specify these:
```
  DB_CONNECTION, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD
```

**Comment by flikites** [comment]
> I'm about to merge it, thank you @nhedger! @flikites these are just for the Github test pipeline, when creating the local MySql instance. To use a custom remote mySQL server, you just need to [customize the docker .env file](https://github.com/JhumanJ/OpnForm#using-a-custom-env-file) to specify these:
> 
> ```
>   DB_CONNECTION, DB_HOST, DB_PORT, DB_DATABASE, DB_USERNAME, DB_PASSWORD
> ```

I'm struggling to get the container to start with mysql - it seems to keep defaulting to postgress.

Should I be putting `msql

**Comment by nhedger** [comment]
`DB_CONNECTION` should be set to `mysql`

**Comment by flikites** [comment]
Any chance I could give you a bounty for a guide on how to deploy this with Docker? @nhedger 

 I am setting the ENV variables as suggested, but it keeps trying to connect to postgres and not mysql.

**Comment by nhedger** [comment]
How do you set your environment variables ? Can you share the file without exposing your credentials?
