### ISSUE TITLE
Inline message without CORS issues

### ISSUE THREAD

**Issue by djmtype** [JhumanJ/OpnForm#174]
Instead of redirecting, is there a way to provide a script that will display an inline message on success or error without CORS issues?

**Comment by JhumanJ** [comment]
Hi, I'm not understand the issue your describing. Please provide more context.

**Comment by kvntapias** [comment]
Currently the cors configuration works in the api for both vue and other frontend clients.
I'm currently making an implementation to consume the endpoints from mobile clients and to prevent me from getting redirected I had to add :

$request->headers->set("Accept", "application/json");

in the Authenticate (Auth) and RedirectIfAuthenticated (Guest) middleware

In this way, it prevents any request via api from returning status 200 + html as a response when the request has really failed.
