### ISSUE TITLE
help.opnform.com offline

### ISSUE THREAD

**Issue by sir-octopus** [JhumanJ/OpnForm#175]
Trying to access https://help.opnform.com/ gives an SSL error which, if ignored, reveals this error:
```
Error 402
Helpdesk plugin inactive.
The plugin for this helpdesk is not active.
The helpdesk owner needs to check their Crisp plan.
```

As a result OpnForms documentation isn't available unless it's been moved elsewhere? If so, can help.opnform.com be redirected there?

**Comment by JhumanJ** [comment]
Hi, for now we cannot afford to pay for Crisp so the documentation is offline. We will soon try to monetize the cloud version of OpnForm and put the documentation back online then.
