### ISSUE TITLE
vite.config valetTls option - enable/disable dynamically

### ISSUE THREAD

**Issue by CISPDEVELOP** [JhumanJ/OpnForm#181]
Hello, in the last changes to main we continued to include valetTls : 'opnform.test' in vite.config.js
is there a way to parameterize this in the main branch via some environment variable
I mention it because in previous commits this option within plugins had been removed and will have to be modified again when merging elsewhere.

plugins: [
     laravel({
       input: [
         'resources/js/app.js'
       ],
       //valetTls: 'opnform.test'
     }),
     vue({
       template: {
         transformAssetUrls: {
           basis: null,
           includeAbsolute: false
         }
       }
     })
   ],

thanks.

**Comment by JhumanJ** [comment]
Hey, thanks for raising this issue. You're right we haven't been consistent with this. Any suggested approach we could take for this?

**Comment by JhumanJ** [comment]
Closing for now
