### ISSUE TITLE
Feature Request: Mailjet Email Support

### ISSUE THREAD

**Issue by floari** [JhumanJ/OpnForm#184]
Hi,

I am trying to use Mailjet to send out mails. I loaded a custom .env file and added the following:

MAIL_MAILER=smtp
MAIL_HOST=xxx.mailjet.com
MAIL_PORT=587
MAIL_USERNAME=api_key
MAIL_PASSWORD=api_secret
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=xx@xx.com
MAIL_FROM_NAME="${APP_NAME}"

I cant get this to work. Can you point me in the right direction?
Thanks!

**Comment by JhumanJ** [comment]
Hey, we'd need an error to help.

**Comment by floari** [comment]
Hi,

no error, there is just no email arriving at the mailjet service.
Which log should I look at? I am using the docker setup.

**Comment by JhumanJ** [comment]
`storage/laravel.log`
