### ISSUE TITLE
Unexpected behavior error - removeBlock,duplicateBlock functions

### ISSUE THREAD

**Issue by CISPDEVELOP** [JhumanJ/OpnForm#196]
Hello, there seem to be problems with the removeBlock and duplicateBlock functions when used from the right sidebar of the block configuration when used immediately after adding a new field.

when you run removeBlock() it removes a different field than the one we just added.

when you run duplicateBlock() it gives the error "Error in v-on handler: "TypeError: newField is undefined""
the duplicateBlock function in
const newField = clonedeep(this.form.properties[this.selectedFieldIndex])
returns undefined and this.selectedFieldIndex is not consistent

**Comment by CISPDEVELOP** [comment]
![imagen](https://github.com/JhumanJ/OpnForm/assets/77641434/7fe5e7b1-5428-4042-bfe5-04d63661cc98)

**Comment by JhumanJ** [comment]
Should be fixed in https://github.com/JhumanJ/notionforms/commit/d51b05aafe72b0f0a213e7eb974009d30edb7a9f. Can you confirm?

**Comment by CISPDEVELOP** [comment]
@JhumanJ  tested, confirm Fixed  #195 !

PD: There is a parsing problem in the Vswitch component for props.value Expected Boolean, got Number with value 0. 
![imagen](https://github.com/JhumanJ/OpnForm/assets/77641434/574b1f6a-e0c3-4957-bb11-8083104fba88)

I am reviewing, and opening a new issue if necessary

thanks!
