### ISSUE TITLE
Unable to start the service, I get a 502 - Bad Gateway.

### ISSUE THREAD

**Issue by billsecond** [JhumanJ/OpnForm#198]
The logs say that the SQL server didn't start.

**Comment by nhonvo** [comment]
Me too. Anyone else having the same problem?

**Comment by JhumanJ** [comment]
Using docker image?

**Comment by felixble** [comment]
Same for me. I am using the docker image. The logs shows the following error:

```
2023/09/14 11:52:05 [crit] 20#20: *1 connect() to unix:/var/run/php-fpm-opnform-site.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: opnform, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm-opnform-site.sock:", host: "localhost:8080"
```

**Comment by billsecond** [comment]
Yes, I am using the Docker image, and I get the same exact error,.  Can someone try it on Docker to duplicate the eissue?

**Comment by nhonvo** [comment]
Which version commit get this error? 🤔 
Has anyone tried another version?
