### ISSUE TITLE
Hot Reload VueJS

### ISSUE THREAD

**Issue by buiphukhuyen** [JhumanJ/OpnForm#212]
### Discussed in https://github.com/JhumanJ/OpnForm/discussions/178

<div type='discussions-op-text'>

<sup>Originally posted by **buiphukhuyen** August 28, 2023</sup>
Hi,

I understand that Hot Reload is a powerful feature that can help streamline development. However, I'm not quite sure how to enable it within the OpnForm project.

Could you please provide guidance or steps on how to set up and use Hot Reload effectively in the OpnForm project? (I using Docker to deploy VPS and I want to translate language system to Vietnamese)

Thanks</div>

**Comment by JhumanJ** [comment]
Hey there! Would you be available for a short call to take a look at that today?

**Comment by JhumanJ** [comment]
By default docker only runs the production script, so I think by ssh-ing to the VM and by running `npm run dev` you should be able to do this!
