### ISSUE TITLE
Mobile Compatibility Issue: Carousel Overflow Rendering Problem

### ISSUE THREAD

**Issue by talktogauravsingh** [JhumanJ/OpnForm#214]
**Issue Description:**

**Problem:** The website (https://opnform.com/) is currently experiencing a mobile compatibility issue due to carousel overflow. When accessed on mobile devices, the carousel content extends beyond the viewport, making it difficult for users to interact with and view the content properly.

**Steps to Reproduce:**

1. Access the website (https://opnform.com/) on a mobile device (e.g., smartphone or tablet).
2. Scroll to the section that includes the carousel component at the bottom of the page
3. Observe that the carousel content extends beyond the screen boundaries, and users are unable to fully interact with or see the content within the carousel.

**Expected Behavior:**

The website should provide a responsive and user-friendly experience on mobile devices. The carousel content should be contained within the viewport, allowing users to easily navigate and view the content.

**Actual Behavior:**

Due to the carousel overflow issue, the content extends beyond the screen, negatively impacting the user experience on mobile devices.

**Environment:**

**Device:** Realme 3
**Browser:** Chrome
**Operating System:** Android
**Website URL:** https://opnform.com/

**Screenshots:**

![Screenshot_2023-09-29-18-13-32-59](https://github.com/JhumanJ/OpnForm/assets/68192053/ed1b5e28-bf16-467c-9ff4-ddf25ee91ce9)
![Screenshot_2023-09-29-18-13-06-69](https://github.com/JhumanJ/OpnForm/assets/68192053/cc164e42-b279-4818-bed0-efad7624a395)

**Comment by JhumanJ** [comment]
Thanks for the report! Fixed in https://github.com/JhumanJ/OpnForm/commit/4fe33b3d96ce250e17a5100cc6404a11b43617c8, deployment should be done in ~5 minutes.
