### ISSUE TITLE
Pro Features on Self Hosted Docker?

### ISSUE THREAD

**Issue by afr4z** [JhumanJ/OpnForm#221]
How does the pro features work on self hosted docker? are they available or like are they free if i host it myself?

**Comment by JhumanJ** [comment]
Hi, all Pro features are accessible for free on the self-hosted version.

**Comment by afr4z** [comment]
but it shows this when i make a form
![image](https://github.com/JhumanJ/OpnForm/assets/98050315/51778a22-4db5-4520-80d6-f804aa7eb901)

**Comment by simondotwhite** [comment]
@afr4z remove the following from you .env and it should work

```STRIPE_KEY=
STRIPE_SECRET=

STRIPE_PROD_DEFAULT_PRODUCT_ID=
STRIPE_PROD_DEFAULT_PRICING_MONTHLY=
STRIPE_PROD_DEFAULT_PRICING_YEARLY=

STRIPE_TEST_DEFAULT_PRODUCT_ID=
STRIPE_TEST_DEFAULT_PRICING_MONTHLY=
STRIPE_TEST_DEFAULT_PRICING_YEARLY=```

**Comment by JonasTrampe** [comment]
I got it running on my server in docker with the above version.
But for 1.2.5 it tells me I need a subscription to add basic submission confirmations.

**Comment by JhumanJ** [comment]
Hey @JonasTrampe please make sure your nuxt `.env` has `NUXT_PUBLIC_PAID_PLANS_ENABLED` set to nothing, ie `NUXT_PUBLIC_PAID_PLANS_ENABLED=`

**Comment by CrazyFire66** [comment]
I have the same problem. I use a docker and the v1.3.1.  In client/.env has the "NUXT_PUBLIC_PAID_PLANS_ENABLED=".

I can't use Submission Confirmation.
