### ISSUE TITLE
Error 404 Form Analytics

### ISSUE THREAD

**Issue by buiphukhuyen** [JhumanJ/OpnForm#225]
### Discussed in https://github.com/JhumanJ/OpnForm/discussions/220

<div type='discussions-op-text'>

<sup>Originally posted by **buiphukhuyen** October 16, 2023</sup>
<img width="2012" alt="Screenshot 2023-10-16 at 08 12 27" src="https://github.com/JhumanJ/OpnForm/assets/43597300/f7cd6ae1-7cd0-4143-a259-f8e1fbe81a73">

How to fix this? Thanks!</div>

**Comment by mchlbwyr** [comment]
@buiphukhuyen in app/Http/Controllers/Forms/FormStatsController.php, getFormStats function change the parameter from:
```php
public function getFormStats(string $formId)
```
to:
```php
public function getFormStats(string $workspaceId, string $formId)
```
