### ISSUE TITLE
Feature Request: Multiple Checkboxes

### ISSUE THREAD

**Issue by simondotwhite** [JhumanJ/OpnForm#240]
Hi,

One thing I think it is missing is the option for multiple checkboxes. I know multi select is there, but potentially that as checkboxes. 

An option to display them either horizontially or vertically would be ideal. 

Example Scenarios:

You have a question called "Please select your Marketing Preferences" and the values are: Email, SMS
You have a question called "Do you agree to being contacted?" and the values are: Yes, No

**Comment by JhumanJ** [comment]
Hi, you can already do that:
![image](https://github.com/JhumanJ/OpnForm/assets/11312432/2437c13a-3e7f-4a1c-88b6-ae5f24e4575d)
