### ISSUE TITLE
MySQL Feature Broke Postgres Migrate

### ISSUE THREAD

**Issue by evelynDickinson** [JhumanJ/OpnForm#241]
I was setting up a new install on Postgres and received this error on a PHP migrate, however PHP migrate worked fine with a mySQL database.

  SQLSTATE[42883]: Undefined function: 7 ERROR:  function json_array() does not exist at character 1882
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL: create table "forms" ("id" bigserial primary key not null, "workspace_id" bigint not null, "title" varchar(255) not null, "slug" varchar(255) not null, "properties" json not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null, "notifies" boolean not null default '0', "description" text null, "submit_button_text" text not null default ('Submit'), "re_fillable" boolean not null default '0', "re_fill_button_text" text not null default ('Fill Again'), "color" varchar(255) not null default '#3B82F6', "uppercase_labels" boolean not null default '1', "no_branding" boolean not null default '0', "hide_title" boolean not null default '0', "submitted_text" text not null default ('Amazing, we saved your answers. Thank you for your time and have a great day!'), "dark_mode" varchar(255) not null default 'auto', "webhook_url" varchar(255) null, "send_submission_confirmation" boolean not null default '0', "logo_picture" varchar(255) null, "cover_picture" varchar(255) null, "redirect_url" varchar(255) null, "custom_code" text null, "notification_emails" text null, "theme" varchar(255) not null default 'default', "database_fields_update" jsonb null, "width" varchar(255) not null default 'centered', "transparent_background" boolean not null default '0', "closes_at" timestamp(0) without time zone null, "closed_text" text null, "notification_subject" varchar(255) not null default 'We saved your answers', "notification_body" text not null default ('<p>Hello there 👋 <br>This is a confirmation that your submission was successfully saved.</p>'), "notifications_include_submission" boolean not null default '1', "use_captcha" boolean not null default '0', "can_be_indexed" boolean not null default '1', "password" varchar(255) null, "notification_sender" varchar(255) not null default 'OpenForm', "tags" jsonb not null default (JSON_ARRAY())))

**Comment by nhedger** [comment]
Hey,

Are you able to provide the steps that led to this error ?

Also, what version of PostgreSQL are you on?

**Comment by nhedger** [comment]
I was able to reproduce the issue with versions of PostgreSQL `<16.x`.

Hopefully, #242 will fix this issue.

In the meantime, you can either:

- use postgres 16.x
- checkout commit 7b3be36ba5a692ace448cc197dbf2599b03446b4 which does not contain the MySQL modifications.
