### ISSUE TITLE
Vue3 Query Builder - Logic Editor

### ISSUE THREAD

**Issue by JhumanJ** [JhumanJ/OpnForm#250]
Hi,
We're in the process of migrating the project to version 3 of Vue. For the field logic editor, we [use this package](https://github.com/rtucek/vue-query-builder) who only has support for vue 2. They aren't too many files in this package, so I believe that it shouldn't be too hard to fork it and to add support for Vue3.

## How to reproduce the compatibility errors
- Check out `vue-3` branch, `npm install`, `npm run dev`
- Open the form editor in the browser
- Click on the blue cog to open field settings for any of the fields
- Open console to see trigger warnings (still working since on `vue-3` branch we still run `@vue/compat`)

## Example errors:
```
[Vue warn]: onActivated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
  at <QueryBuilderGroup config= {operators: Array(2), rules: Array(3), colors: Array(6)} query= 
```
or 
```
[Vue warn]: onUpdated is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement. 
  at <QueryBuilderGroup config= 
```

## Acceptance criteria
- We need an open-source fork of this `vue-query-builder` package
- And a PR to the `vue-3` branch, replacing the `rtucek/vue-query-builder` dependency with the new query builder, essentially fixing these issues!

Thank you!

**Comment by JhumanJ** [comment]
!bounty $150

**Comment by rishi-raj-jain** [comment]
Can I be assigned this?

**Comment by rishi-raj-jain** [comment]
on it already :D

**Comment by rishi-raj-jain** [comment]
@JhumanJ 

Which URL do I open the form editor in?

**Comment by rishi-raj-jain** [comment]
@JhumanJ 

Here's how you can tip me:

https://docs.algora.io/tipping#:~:text=username%20as%20in-,/tip%20%24amount%20%40user,-Previous

**Comment by JhumanJ** [comment]
/tip $75 @rishi-raj-jain 

Here's your half! 

@kwesterfeld2 can I also pay you via algora?

**Comment by JhumanJ** [comment]
Closing this! @kwesterfeld2 can I also pay you via algora?

**Comment by kwesterfeld2** [comment]
You guys are a trip.

I am not looking to get paid.

Glad you guys made use of the work, but you should pay the original author something, not me.

Good luck!
________________________________
