### ISSUE TITLE
Migration from Vue.js SPA to Nuxt with Universal Rendering

### ISSUE THREAD

**Issue by JhumanJ** [JhumanJ/OpnForm#252]
# Migration of OpnForm from Vue.js SPA to Nuxt with Universal Rendering

### Summary
We're looking for contributions to migrate our Vue.js Single Page Application (SPA) for OpnForm ([OpnForm Repository](https://github.com/jhumanj/opnform)) to a Nuxt application using universal rendering. This migration is crucial for enhancing performance, SEO, and accessibility across our projects, including NoteForms.

### Key Objectives
- **Transform to Nuxt App**: Convert the Vue3 SPA to a Nuxt app with universal rendering.
- **Scope**: Focus on local functionality. Deployment pipeline and Docker image modifications will be addressed later.
- **Project Structure**: Maintain a single repo structure with the Nuxt app in a `client` folder.
- **Preserve Existing Functionalities**:
  - Maintain all routes and middleware.
  - Keep front-end route paths unchanged.
  - Implement server-side data fetching for specific routes.
  - Replace `seo-meta` mixin with `useSeoMeta` ([Nuxt SEO Meta](https://nuxt.com/docs/getting-started/seo-meta#useseometa)).
- **Documentation**: Update npm scripts and README for Nuxt-related changes.

### Acceptance Criteria
- Create a Nuxt PR to the `vue3` branch.
- Ensure the application functions correctly locally.
- Include updated documentation in the PR.

### Collaboration
Feel free to ask questions or request clarifications anytime.

**Comment by ezhil56x** [comment]
@JhumanJ Can I work on this?

**Comment by JhumanJ** [comment]
Hey, thanks for reaching out @ezhil56x . Are you experienced with nuxt and vue?
Also I discussed few hours ago about this task with @rishi-raj-jain, and he said he'd do it. Let's give me a few hours to see if it's still the case.

**Comment by rishi-raj-jain** [comment]
@JhumanJ 

Yes, I'm more than hella interested in getting this done!

**Comment by rishi-raj-jain** [comment]
Thank you 🙏

**Comment by JhumanJ** [comment]
I just assigned it to you @rishi-raj-jain. Please update us on progress :) 
I'll let you guys discuss and see if you feel like collaborating @ezhil56x

**Comment by rishi-raj-jain** [comment]
Sure thing!

**Comment by ezhil56x** [comment]
@rishi-raj-jain Are you up for collaborating?

**Comment by rishi-raj-jain** [comment]
@ezhil56x 

Would like to attempt this first, I've been taking on migrations recently and wanting to getting good at them.

Will definitely loop you in if require your any help!

**Comment by rishi-raj-jain** [comment]
I've reached out to @danielroe for his guidance if there's any integration of Laravel + Nuxt3 that can replace the things and help smoothly migrate to Nuxt3.

**Comment by JhumanJ** [comment]
Just took a detailed look to https://github.com/fumeapp/laranuxt, and it's a great inspiration, especially for config and folder structure!

**Comment by nhedger** [comment]
I would have loved to take on the challenge, but since @rishi-raj-jain is already assigned to the issue, I'll instead take the opportunity to say that my https://github.com/nhedger/nuxt-sanctum package could help with the authentication part (sanctum).

If you end up not doing it, I'd appreciate it if you let me know @rishi-raj-jain.

Good luck!

**Comment by nhedger** [comment]
With Sanctum you would also call your Laravel API, the only difference being that you do not need to handle tokens for authenticating the first-party frontend. You use session cookies that handle that for you, which is more convenient and more secure. Backend and frontend apps must share the same top-level domain, though.

**Comment by JhumanJ** [comment]
Thanks for your interest @nhedger! Sanctum is great, tbh we didn't use it this project is a fork from another project, which I created when I didn't know about Sanctum. I guess for now it's just easier to not use it (less code changes), but it could be interesting to investigate this later on

**Comment by nhedger** [comment]
Is there a requirement **NOT** to use Nuxt pages here?

**Comment by JhumanJ** [comment]
There isn't, but the existing route path can't change :(

**Comment by JhumanJ** [comment]
We're working on this internally, so closing this!
