### ISSUE TITLE
docker not working , header_mismatch, customDomainHeaderValue: undefined

### ISSUE THREAD

**Issue by changchichung** [JhumanJ/OpnForm#295]
docker logs
```
2024-01-26 02:54:27 (13.4 MB/s) - ‘/root/.nvm/.cache/bin/node-v20.11.0-linux-x64/node-v20.11.0-linux-x64.tar.xz’ saved [25522792/25522792]

Computing checksum with sha256sum
Checksums matched!
Now using node v20.11.0 (npm v10.2.4)
Creating default alias: default -> 20 (-> v20.11.0 *)
Now using node v20.11.0 (npm v10.2.4)
/usr/local/bin/nuxt-wrapper.sh: line 12: /app/.nuxt.env: No such file or directory
/usr/local/bin/nuxt-wrapper.sh: line 14: env.sh: No such file or directory
Listening on http://[::]:3000
Redirecting to main domain {
  reason: 'header_mismatch',
  customDomainHeaderValue: undefined,
  host: '192.168.100.2'
}
192.168.100.55 - - [26/Jan/2024:02:54:35 +0000] "GET /?utm_source=failed_custom_domain_redirect HTTP/1.1" 301 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 OPR/106.0.0.0"
```

I also try cp .docker.env .env and mapping .env to container, my docker command
```
docker run --name opnform -v $PWD/.env:/app/.env -v $PWD/my-opnform-data:/persist -p 8007:80 km/opnform
```
and part of my .env file
```
 cat .env
APP_NAME="OpnForm"
APP_ENV=local
APP_KEY=base64:7CPY4w4JNasdasdomY=
APP_DEBUG=false
APP_LOG_LEVEL=debug
APP_URL=http://192.168.100.2:8007
```

so , where should I modify the customdomain value ? ?

**Comment by JonasTrampe** [comment]
I have the same problem.

**Comment by Jogai** [comment]
See #283

**Comment by JhumanJ** [comment]
Hi, can you try setting your docker client env to:
```
NUXT_PUBLIC_CUSTOM_DOMAINS_ENABLED=false
NUXT_PUBLIC_ENV=local
NUXT_PUBLIC_PAID_PLANS_ENABLED=false
NUXT_PUBLIC_S3_ENABLED=false
``` 
We probably need to update the default settings to this

**Comment by JhumanJ** [comment]
The issue comes from this code: [/client/lib/utils.js#L75-L81](https://github.com/JhumanJ/OpnForm/blob/428ab4f6cf0ce789d8f1b2b92cf034a9db59c5fc/client/lib/utils.js#L75-L81)
```js
export const customDomainUsed = function() {
  const config = useRuntimeConfig()
  const appDomain = getDomain(config.public.appUrl)
  const host = getHost()

  return host !== appDomain && getDomain(host) !== appDomain
}
```
Please make sure that `NUXT_PUBLIC_APP_URL` has the right value? It should be the same as your app URL, so I believe `192.168.100.2` in your case

**Comment by JhumanJ** [comment]
@changchichung there are 2 `.env` files, one for client and one for Nuxt, please make sure to pass the nuxt .env to nuxt

**Comment by JhumanJ** [comment]
I'll give this a proper try this afternoon, could you please try to send me all the steps to reproduce?

**Comment by JhumanJ** [comment]
Hi there, I just went through the process again, without changing any .env files and it worked just fine. I only ran `docker run --name opnform -v $PWD/my-opnform-data:/persist -p 8000:80 --platform linux/amd64  jhumanj/opnform`

Can you please try this yourself without customizing the .env files?

**Comment by JhumanJ** [comment]
I just simplified the custom domain handling for docker environment to avoid this issue, can please try again pulling the latest docker image?

**Comment by JhumanJ** [comment]
We're working on it!

**Comment by JhumanJ** [comment]
Fixed! I'll draft the release now! https://github.com/JhumanJ/OpnForm/pull/312
