### ISSUE TITLE
Feature: support email notifications

### ISSUE THREAD

**Issue by pravi** [JhumanJ/OpnForm#296]
I think getting email notifications for new submissions is a crucial feature for many forms like a contact form or call for volunteers form. Some of the forms we migrated to formbricks.com because they offer that option. It'd be nice if opnform supports it as well.

**Comment by JhumanJ** [comment]
Hi @pravi, feature is already there!
https://help.opnform.com/en/article/can-i-receive-notifications-on-form-submissions-134svqv/
