### ISSUE TITLE
Feature Request: Left, right and center alignment and width settings for buttons and captcha

### ISSUE THREAD

**Issue by ayntk-ai** [JhumanJ/OpnForm#307]
I know I can do this with css but please give us a UI setting in the next version that allows us to align the submit button left, right or centre and also align the next button left right or centre and the previous button left, right or centre --> Also the option to make the submit button full width of the form so it is as wide as the form field would be great.

Tasks:

- [ ] Left, right, centre align submit button
- [ ] Set a with on the submit button -> form width, full width or normal width (normal is as it is now)
- [ ] Left, right, centre align next button
- [ ] Left, right, center align previous button
- [ ] Let us set a custom width for the next buttons
- [ ] Let us set a custom width for the previous buttons
- [ ] Also allow us to align the captcha left, right or centre

Please implement this for the next version, it would greatly improve the forms.

**Comment by JhumanJ** [comment]
Hi thanks for your feature request. Please use[ our dedicated feature request board ](https://opnform.featurebase.app/)and keep GH issues for technical problem, or open-source contributions.
