### ISSUE TITLE
Feature Request: WYSIWYG Field

### ISSUE THREAD

**Issue by ayntk-ai** [JhumanJ/OpnForm#309]
- Add a fully styled WYSIWYG field --> not the default styling which looks very bad, but a cleanly styled WYSIWYG field with options for the colours of text, background, icons and so on would be nice.

**Comment by JhumanJ** [comment]
Hi thanks for your feature request. Please use[ our dedicated feature request board ](https://opnform.featurebase.app/)and keep GH issues for technical problem, or open-source contributions.
