### ISSUE TITLE
Can't add conditions to a Text/Code Block.

### ISSUE THREAD

**Issue by JonasTrampe** [JhumanJ/OpnForm#317]
I am not able to add conditions to text/code block and safe it.

Create a new (empty) Form.
Add a Checkbox
Add a text/code block
Hide the block (may not be necessary)
Add condition "is checked" to the block
Try to safe

Result:
Popup 
"The logic actions for Text Block are not valid.
 - The logic actions for Text Block are not valid."

Console:
"POST https://forms.larpmanager.de/api/open/forms 422 (Unprocessable Content)"
"/api/open/forms:1](app-1b4cbf77.js:6) "

**Comment by JhumanJ** [comment]
Thanks for the detailed report! Fixed in https://github.com/JhumanJ/OpnForm/commit/b7c4f8e010043b06138e0ef7b34b2fd76427465e!
