### ISSUE TITLE
Unable to register or login when self hosting via Docker

### ISSUE THREAD

**Issue by JZafarr** [JhumanJ/OpnForm#319]
Hi there,
I'm able to install the app via docker and docker compose and can access the interface with the local IP address but when i try to publish a form it asks to register or log-in.
When I try to do that and click on the "Register" button after filling my details, nothing happens. Same thing happens when I try to login and press the "Login to continue" button.

Any suggestions would be great.
Thanks.

**Comment by JhumanJ** [comment]
Hi, can you please provide logs from both the browser console and the docker image?

**Comment by JZafarr** [comment]
Here is my browser console log
https://gist.github.com/JZafarr/c608731c7d19260cd50054a0178e2269

I just checked the docker logs and they are just bunch of 200 responses from the browser, let me know if you still need those as it shows my domain name in there

**Comment by JZafarr** [comment]
Here are the updated logs
Console Logs
https://gist.github.com/JZafarr/d000228b9f29edbeab38ad791cd83aef

Docker logs
https://gist.github.com/JZafarr/2508c3831955bc2cc53d149b3627c573

**Comment by rimonsalah** [comment]
Any solution?

**Comment by karpadiem** [comment]
@JZafarr @changchichung @rimonsalah I was having the same issue. I fixed it by changing the variables in the /app/client/.env file.

`NUXT_PUBLIC_APP_URL=http://localhost/
NUXT_PUBLIC_API_BASE=http://localhost/api`

Change to:
`NUXT_PUBLIC_APP_URL=http://yourfulldomain.com/
NUXT_PUBLIC_API_BASE=http://yourfulldomain.com/api`

**Comment by rimonsalah** [comment]
> @karpadiem
> 
> would u please share your .env file and docker command ? I also did updated NUXT_PUBLIC_APP_URL & NUXT_PUBLIC_API_BASE , but it doesn't help.

Please restart the container

**Comment by JZafarr** [comment]
wait before you close this please, I havent had the chance to test it yet, I wasnt even using an environment file.

**Comment by JhumanJ** [comment]
The docker setup should create both .env files for you (within the docker image). However if you need to customize the .env files - in the case of using a cusotm domain for instance then you do need to [set the .env files](https://github.com/JhumanJ/opnform?tab=readme-ov-file#using-custom-env-files).

Added some more guidance in the readme https://github.com/JhumanJ/OpnForm/commit/0b3fe439898ece6f784adcb0239db9847463caf4, closing this thanks!

**Comment by rimonsalah** [comment]
after change the .env we are able to login but when we create a form. we cant preview page not found error
![image](https://github.com/JhumanJ/OpnForm/assets/46981592/2fb00bc9-5a37-4fac-9ca5-6b37da119b0f)

then we cant log in any more till we restart the conatiner
