### ISSUE TITLE
Implementing Localization in OpnForm

### ISSUE THREAD

**Issue by buiphukhuyen** [JhumanJ/OpnForm#323]
Hello OpnForm Team,

I'm a user from Vietnam, and I really appreciate the open-source project OpnForm because it meets my needs. 

However, I've encountered difficulties using the current system as it doesn't support Localization. I hope that you and the team can add this feature so that the community can contribute and build for various countries without language barriers. 

Thank you!

**Comment by JhumanJ** [comment]
Hey thanks for the request. We do have plans for this, but we can't guarantee an ETA at this point. I'm closing this, you can upvote this feature request here: https://opnform.featurebase.app/p/translation-of-all-form-text
