### ISSUE TITLE
Upload file types are case sensitive

### ISSUE THREAD

**Issue by karpadiem** [JhumanJ/OpnForm#329]
For an upload field, I have provided a list of valid file types. EG: "jpg,jpeg,png,heic,tiff,pdf,bmp,gif,webp"

If a file is uploaded with an extension that is all caps eg: "img_1001.JPG" the validation fails the the file can not be uploaded.

Modifying the valid file types to something like "JPG,jpg,jpeg,png,heic,tiff,pdf,bmp,gif,webp" does not work as a work around.

Im assuming that the valid file types gets normalized to lower case, but perhaps the uploaded file extension should be normalized to lowercase as well?

**Comment by JhumanJ** [comment]
Thanks, fixed in https://github.com/JhumanJ/OpnForm/commit/2ac9b96284927cd79b0df184e973279211be850c
