### ISSUE TITLE
Times out when self-hosting via docker

### ISSUE THREAD

**Issue by JZafarr** [JhumanJ/OpnForm#331]
I can login and can create forms but randomly it times out usually around 3-4 minute mark and then does the same thing of not being able to login or register.
You have to restart the container for it to work again and even then it works for a few minutes and then times out again and so on.....

Here are the console logs:
https://gist.github.com/JZafarr/274dc678d446e10b050c06fd15df4c24

**Comment by JZafarr** [comment]
Usually starts when you check your submissions and analytics and then it times out

**Comment by rimonsalah** [comment]
I have the same issue but also not able to view or share form

**Comment by JZafarr** [comment]
here are the docker logs, looks like something to do with Redis

https://gist.github.com/JZafarr/2849905a949fb2ef79b33ed32a6520e8

**Comment by JZafarr** [comment]
also there is recursive creation of storage directory within itself, not sure if its related but just letting you know

app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage# cd storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage# ls
app  framework  logs  storage
root@dc80a5e8b425:/app/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage/storage#

**Comment by jessestippel** [comment]
Also getting this issue, can't view the forms and after a certain period of time it simply stops responding. Running on Docker.

**Comment by JhumanJ** [comment]
We'll look at the docker issues next week, thanks for reporting this.

**Comment by JZafarr** [comment]
any update on this issue?

**Comment by JhumanJ** [comment]
Fixed in https://github.com/JhumanJ/OpnForm/pull/369
