### ISSUE TITLE
Token issue

### ISSUE THREAD

**Issue by Pratham2404** [JhumanJ/OpnForm#336]
On refresh redirecting to login page and token is removed from cookies

**Comment by yagnesh1406** [comment]
I am also facing the same issue.

**Comment by SmitB1810** [comment]
Same issue Mrs.Pratham. If you find any solution let me know. Thank you.

**Comment by JhumanJ** [comment]
We'll look at the docker issues next week, thanks for reporting this.

**Comment by JhumanJ** [comment]
Can you please share the logs?
