### ISSUE TITLE
Docker deployment on Railway - Can´t login / register account ?

### ISSUE THREAD

**Issue by Innovathor69** [JhumanJ/OpnForm#349]
Hi there,

i just deployd a new docker instance of opnform. But for some reason, i cant login / register an account? There is no environment-variable set. Further more, when i register just nothing happens. 

Is there a defaul user/pass? Is there an Environment-Variable to set?

Thanks a lot

**Comment by sebastian2012** [comment]
Hi!
I deployed opnform on docker with Debian System.
I have create an .env-File. 
After activating debug-Log, I found the following in logs/laravel.log:
[2024-03-21 09:33:25] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "users" does not exist
LINE 1: select count(*) as aggregate from "users" where "email" = $1

I Think, that the Databases are not correct created ... 
Best Regards!

**Comment by JhumanJ** [comment]
Can you please share some logs? A database should be created, and in the logs of image instanciation you should be able to see the migrations running 
```

   INFO  Preparing database.

  Creating migration table ........................................ 170ms DONE

   INFO  Running migrations.

  2014_10_12_000000_create_users_table ............................. 67ms DONE
  2014_10_12_100000_create_password_resets_table ................... 47ms DONE
  2017_12_07_122845_create_oauth_providers_table .................. 106ms DONE
  2019_05_03_000001_create_customer_columns ........................ 13ms DONE
  2019_05_03_000002_create_subscriptions_table ..................... 68ms DONE
  
  .....
```

**Comment by sebastian2012** [comment]
[docker.log](https://github.com/JhumanJ/OpnForm/files/14862542/docker.log)
Hi!
I have attached the log from docker logs opform (docker.log) I don't find any hints to create migration tables. 
[laravel.log](https://github.com/JhumanJ/OpnForm/files/14862568/laravel.log)
Oh, I can attach laravel.log ... done :-)

Best Regards!

**Comment by dontoptal** [comment]
Okay, I think this is the issue https://laracasts.com/discuss/channels/laravel/production-server-every-time-asks-do-you-really-wish-to-run-this-command

@sebastian2012 Do you have `APP_ENV=production` in your .env file?  I think the current docker config might be incompatible with that setting.  I'm working on a fix now.

**Comment by JhumanJ** [comment]
Resolved in https://github.com/JhumanJ/OpnForm/pull/372! Now will update docker image

**Comment by sebastian2012** [comment]
Hi,

works perfect ... thanks!
