### ISSUE TITLE
Question: is it possible to embed in other apps?

### ISSUE THREAD

**Issue by cdgn-coding** [JhumanJ/OpnForm#387]
I want to empower another app with the feature of being able to create forms. I think this might be possible with OpenForm if:

1. OpenForm is able to setup forms through an API
2. It is possible to embed the form builder UI in another app

Do you think this is possible with OpenForm? How complex would it be to implement this in case this it is not already supported? 

Thanks!

**Comment by JhumanJ** [comment]
Hi there, it's not currently possible and we don't have short term plans of working on this.
