### ISSUE TITLE
Allow classic radio button or checkbox style for single/multi select

### ISSUE THREAD

**Issue by TheChilliPL** [JhumanJ/OpnForm#396]
As in the title, it would be nice if the form builder allowed showing selections as either radio buttons or checkboxes instead of normal buttons. I believe it would make it clearer for the people filling the form

**Comment by JhumanJ** [comment]
Hi, please check this: 
![CleanShot 2024-05-07 at 12 04 25@2x](https://github.com/JhumanJ/OpnForm/assets/11312432/cbf7f105-90c1-4b42-afc4-ae7dec332f3e)

**Comment by TheChilliPL** [comment]
It doesn't show the radios nor checkboxes when nothing is selected. It looks like a bunch of buttons
