### ISSUE TITLE
Multiple logic blocks with different actions?

### ISSUE THREAD

**Issue by TheChilliPL** [JhumanJ/OpnForm#397]
The form should allow introducing multiple logic blocks to each form element, so that different conditions may result in different actions (something may make an input obligatory, while something else might make it disabled, etc.)

**Comment by JhumanJ** [comment]
Hi, please check https://help.opnform.com/en/article/how-do-i-add-some-logic-to-my-form-1lmguq5/.

**Comment by TheChilliPL** [comment]
Still doesn't allow different actions for different conditions of the same element
