### ISSUE TITLE
Integrating an Email Capture Feature with OpnForm Cloud Using HTML and JavaScript

### ISSUE THREAD

**Issue by macmatrix** [JhumanJ/OpnForm#412]
I use OpnForm Cloud, and while it's excellent, customization options feel somewhat limited. I'm looking to integrate an email capture feature where the submit button is within the form, not a standalone button. See image
![IMG_8775](https://github.com/JhumanJ/OpnForm/assets/54081639/ad81d7a4-4895-4dff-8aa9-f5418ce10d64)

I'm not certain if there are APIs available for this purpose, but utilizing them would be ideal. Here are the potential steps I'm considering:

1. Design your form using HTML.
2. Employ JavaScript to execute a POST request to the OpnForm API when the form is submitted.
3. Ensure the POST request includes the form data in the body and incorporates your OpnForm API key in the request headers.

Any suggestion?

**Comment by JhumanJ** [comment]
Hi there, although this could be achieved by using our API and some custom javascript, we don't want to offer support for this now, as we're focused on building a complete form builder - not just the a back-end for forms. Feel free to do it, but we won't be able to help with this for now
