### ISSUE TITLE
Same implementation but output different in localhost and in a domain name.

### ISSUE THREAD

**Issue by alloke613** [JhumanJ/OpnForm#414]
I have deployed the OpnForm in Docker, when I access through localhost or IP address, it will show as below which looks good:
<img width="1680" alt="Screenshot 2024-05-20 at 11 46 15 PM" src="https://github.com/JhumanJ/OpnForm/assets/985289/2ec1525a-7472-4add-a826-59d9ad2c6045">

However, when I put it to subdomain of my domain name, it became as shown in the image below:
<img width="1680" alt="Screenshot 2024-05-20 at 11 46 00 PM" src="https://github.com/JhumanJ/OpnForm/assets/985289/fdf7b6b6-9974-4363-995b-fa0f132b9998">

I wonder what causing the code to be missing, is there any example for the environment variables available for docker?

**Comment by LuckVintage** [comment]
Hi,

Are you using Cloudflare? I also had this problem and managed to resolve it by disabling the 'Auto Minify' option for HTML in the Cloudflare Dashboard.

![image](https://github.com/JhumanJ/OpnForm/assets/54641441/a3747610-5b89-4648-96cc-cf1c8851e0fa)

**Comment by alloke613** [comment]
Great. I am using Cloudflare. Thanks for the solution. I did resolve it. Btw, this auto minify feature is going to deprecate soon too.

> Hi,
> 
> Are you using Cloudflare? I also had this problem and managed to resolve it by disabling the 'Auto Minify' option for HTML in the Cloudflare Dashboard.
> 
> ![image](https://private-user-images.githubusercontent.com/54641441/334885857-a3747610-5b89-4648-96cc-cf1c8851e0fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNTI2NjEsIm5iZiI6MTcxNzA1MjM2MSwicGF0aCI6Ii81NDY0MTQ0MS8zMzQ4ODU4NTctYTM3NDc2MTAtNWI4OS00NjQ4LTk2Y2MtY2YxYzg4NTFlMGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA2NTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTlmZDNkNjRjNjdiZmJhNGY2MWY3MjFkYzZlMDU2YWE2MjhhZTVmOGJmYWU5YzEwZjZkYmQ3OGUxMTEwYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fRkwKOLskdeA48Ur_aBZTM46D9jfunzUE9K0gXd8CGA)
