### ISSUE TITLE
hCaptcha secret key when deploying OpnForm via Docker

### ISSUE THREAD

**Issue by LuckVintage** [JhumanJ/OpnForm#428]
Hello there,

I am self-hosting OpnForm on Docker. Everything is working great, but I'm a little confused how to get hCaptcha working.

I am using the NUXT Docker .env file from https://github.com/JhumanJ/OpnForm/blob/main/client/.env.docker, but there doesn't seem to be an option to specify my hCaptcha secret key. I also can't find anything hCaptcha related in the Laravel .env file here: https://github.com/JhumanJ/OpnForm/blob/main/.env.docker.

Where can I specify my hCaptcha secret key when deploying OpnForm via Docker?

Many Thanks 👍

**Comment by JhumanJ** [comment]
Hey - curious to hear more about your setup. Did you use our docker image?
Here are the env variable that you need to fill:
- In the Laravel env
https://github.com/JhumanJ/OpnForm/blob/68b610bc15507498a385a154100e3710e6ca7156/.env.example#L70-L71
- In the Nuxt env
https://github.com/JhumanJ/OpnForm/blob/68b610bc15507498a385a154100e3710e6ca7156/client/.env.example#L10

I'm resolving this but feel free to share more about your setup below!

**Comment by LuckVintage** [comment]
Hi!

Thank you for your reply. I am running Docker version 24.0.5 on Ubuntu 22.04.1. I did indeed use your Docker image.

I added the env variables you suggested, but hCaptcha is still having issues. Before this, the Captcha was successfully loading but would obviously fail to validate when submitting the form due to the lack of the secret key. With the env variables from your reply, the Captcha no longer loads and says "hCaptcha has failed to initialize. Please see the developer tools console for more information." Upon checking the console, it claims that there is a missing sitekey.

My custom-laravel-env-file.env: https://pastebin.com/Fi3ccd8q
My custom-nuxt-env-file.env: https://pastebin.com/FM1vyBGW

Many Thanks.
