### ISSUE TITLE
Will it support ARM64 ?

### ISSUE THREAD

**Issue by abbsay** [JhumanJ/OpnForm#433]
When I install it on the Oracle Cloud Arm64 ,

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/bin/supervisord: exec format error

**Comment by JhumanJ** [comment]
Hi there, not our priority for now. We've opened a new issue to improve our docker setup, but ARM64 support is not a priority for us right now!
