### ISSUE TITLE
Dockerfile atypically starts Postgres and Redis

### ISSUE THREAD

**Issue by ben-pr-p** [JhumanJ/OpnForm#438]
I tried to self deploy this, and I noticed [the Docker image](https://hub.docker.com/r/jhumanj/opnform) starts Postgres and Redis inside of the same container.

This is a bit atypical, and makes configuring backups, generally managing the Postgres deployment, and scaling harder.

I would suggest having the Docker image just deploy the server (seems like there's 2 servers, one Laravel and one Nuxt), and then having them connect to Postgres and Redis over the network.

It's then the users responsibility to self host Postgres or use a managed instance

**Comment by flece** [comment]
also this way your dockerimage gets way smaller.  you dont have to ship the hole stack you are using to run OpnForm. Thats why you are using docker in the first place. There are planty of Guides on this topic.

* https://adevait.com/laravel/containerizing-laravel-applications-with-docker

**Comment by JhumanJ** [comment]
Hi, I understand and agree with what you shared @ben-pr-p. You can still use an external database by changing the .env file, but the setup is bit clunky. None of us is really experimented with Docker but it seems like it's time to improve this, I created a new issue here https://github.com/JhumanJ/OpnForm/issues/445, and I'd love to get your feedback on it @flece @ben-pr-p
