### ISSUE TITLE
Share feature does not work with self-hosted version

### ISSUE THREAD

**Issue by ravensorb** [JhumanJ/OpnForm#495]
Not sure if this is a bug or a feature request -- in the self hosted version it seems that OpnForms does not use the current FQDN nor does it allow one to be set for the share feature.  I do understand that the ability to support multiple custom domains is part of the pro SaS version -- that said it would be nice to at least be able to set the default to be used (or use the current one from the browser) as the standard behavior. 

![image](https://github.com/user-attachments/assets/1cc63c12-a8b5-4546-88a7-21614b24cca5)

**Comment by JhumanJ** [comment]
Resolved in https://github.com/JhumanJ/OpnForm/pull/513. Please make sure to follow instructions
