### ISSUE TITLE
Confusion about OpnForm's Terms & Conditions

### ISSUE THREAD

**Issue by pisgor** [JhumanJ/OpnForm#496]
In OpnForm's Terms & Conditions, one of the restriction imposed is that "You agree not to, and you will not permit others to: Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website." Isn't modifying the source code also means to modify part of the website?

**Comment by JhumanJ** [comment]
Sorry about the confusion - we need to resolve this issue. This is supposed to be for the "cloud" version but of course does not apply to the open-source code (see license)
