### ISSUE TITLE
Documentation/Howto for docker-compose missing

### ISSUE THREAD

**Issue by HannesMC** [JhumanJ/OpnForm#508]
Hi folks,

I am not a developer nor do I intend to become one. So please forgive me if I am completely wrong in sharing my concerns here. In order to be able to test OpnForm quickly and easily, it is always an advantage to find all the necessary things in a short howto. I find that sample files can be very helpful. 

Here is a suggestion on how to get your project up and running quickly and easily using a docker-compose file. It would be great if you could add a sample file to your repository. 

Below a docker-compose example. Its just an example and it works also in portainer (self tested). 

`version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opnform
      MYSQL_USER: opnform
      MYSQL_PASSWORD: opnformpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - opnform-network

  opnform:
    image: jhumanj/opnform:latest
    container_name: opnform
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: opnform
      DB_USERNAME: opnform
      DB_PASSWORD: opnformpassword
      APP_URL: http://localhost
      NUXT_PUBLIC_APP_URL: http://localhost
      NUXT_PUBLIC_API_BASE: http://localhost/api
    ports:
      - "8085:80"
    volumes:
      - opnform-data:/persist
    depends_on:
      - mysql
    networks:
      - opnform-network

volumes:
  mysql-data:
  opnform-data:

networks:
  opnform-network:`

**Comment by JhumanJ** [comment]
Thanks for the help, we just released our docker compose setup. https://github.com/JhumanJ/OpnForm/pull/513
