### ISSUE TITLE
Question: Can I change the generated Link to not include an ID

### ISSUE THREAD

**Issue by Felitendo** [JhumanJ/OpnForm#529]
Right now when I complete a Forms Setup it gives me a link like this:

http://forms.domain.tld/forms/some-title-le4iyv

Can I change this to generate a link like this?:

http://forms.domain.tld/forms/some-title

**Comment by Felitendo** [comment]
Also how can I enable https by default? So in the end it generates a link like this?:

https://forms.domain.tld/forms/some-title

**Comment by JhumanJ** [comment]
There's now way to do this from the UI currently. It can be done directly from the database.
