### ISSUE TITLE
Issue with /api/upload-file and /api/password/email on self-hosted 

### ISSUE THREAD

**Issue by asrulmunir** [JhumanJ/OpnForm#533]
I like this project and manage to get it install on Google Cloud Platform using docker.

OpnForm would be the perfect platform for my use case except for these 2 issues:

1- I can't use the upload files feature

`Failed to load resource: the server responded with a status of 500 ()`

2- I can't send out emails (invite users and password reset)

`FetchError: [POST] "/api/password/email": 500 `

I'm not sure is there anything that missing:

.env:

MAIL_MAILER=smtp
MAIL_HOST=live.smtp.mailtrap.io
MAIL_PORT=587
MAIL_USERNAME=api
MAIL_PASSWORD=843xxxxx1b75
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=mailtrap@mydomain.com
MAIL_FROM_NAME="${APP_NAME}"

As for Minio, I can't see any Minio service is running from docker ps.

**Comment by ados1989** [comment]
I have the same problems

**Comment by asrulmunir** [comment]
Solved the upload issue and password reset email.

But still having issue on email invite.

Logs:

2024-08-24 07:37:09 App\Mail\UserInvitationEmail ................... RUNNING
  2024-08-24 07:37:09 App\Mail\UserInvitationEmail ............. 203.19ms FAIL
[2024-08-24 07:37:09] local.DEBUG: Un-handled Exception: Please provide a valid cache path. {"exception":"[object] (InvalidArgumentException(code: 0): Please provide a valid cache path. at /usr/share/nginx/html/vendor/laravel/framework/src/Illuminate/View/Compilers/Compiler.php:67)

**Comment by ados1989** [comment]
How do you solved the upload issue?

**Comment by ashwin-arrivae** [comment]
Hi @asrulmunir  can you share the solution

**Comment by JhumanJ** [comment]
We've seen this - will fix soon

**Comment by ashwin-arrivae** [comment]
Is there any timeline to fix this,as we are evaluating this service.

**Comment by JhumanJ** [comment]
Hi all - the image upload have been resolved - please re-create the container using latest images. For the email reset issue it's most probably a config issue so please share more details in a new issue
