### ISSUE TITLE
New install (self-hosted) inoperable

### ISSUE THREAD

**Issue by LeeBuckland** [JhumanJ/OpnForm#538]
Creating a new installation on a new fully patched Linux environment (AlmaLinux in my case, but I see users of other distros having same issue) does not accept default credentials to make the system operational. May not be related but for context, I attempted this after patching an existing installation resulted in forms not rendering.

**Comment by JhumanJ** [comment]
Hi there, just run the command `app:init-project`. It's new and only runs on fresh DB install so you might have to re-create the DB. Easiest thing would probably be to redeploy the whole thing (won't be like this in the future but we're finalizing the final structure of the project)

To run the command: Make sure your Docker containers are running. If they're not, start them with:
```docker-compose exec api php artisan app:init-project```

**Comment by LeeBuckland** [comment]
Executing this command results in:
Users already exist in the database or the User table is not empty. Aborting initialization.

**Comment by LeeBuckland** [comment]
It’s a brand new installation and the default credential ***@***.******@***.***> does not work.

**Comment by Darkstepan** [comment]
I have exactly the same issue.

**Comment by LeeBuckland** [comment]
It’s a brand new installation and the default credential admin@... does not work. I have not yet been able to login in order to create any additional user. I believe this issue to be related to recent updates to Linux.

**Comment by JhumanJ** [comment]
Fixed!

**Comment by LeeBuckland** [comment]
Thanks Julien - That's appears to have fixed the issue. I was also able to fix an existing installation by pulling down the latest docker images.
