### ISSUE TITLE
Deploy in Kubernetes

### ISSUE THREAD

**Issue by sergiotocalini** [JhumanJ/OpnForm#545]
I am facing issues with setting up the proper ingress rules. The nginx.conf is not possible to replicate into an ingress resource, can you please help me?

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opnform
  namespace: opnform
  annotations:
    meta.helm.sh/release-name: opnform
    meta.helm.sh/release-namespace: opnform
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $http_connection;
    nginx.ingress.kubernetes.io/proxy-http-version: '1.1'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
rules:
    - host: opnform.local
      http:
        paths:
          - path: /(.+\.php)(/.+)$
            pathType: ImplementationSpecific
            backend:
              service:
                name: worker
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 3000
```

I tried with several path base configurations but there were always redirection problems.

Thanks in advance.

**Comment by sergiotocalini** [comment]
Hi @JhumanJ,

Thanks for replying to my request.
I am more than happy to help you with it. Actually, I am creating a helm chart for OpnForm and just the ingress rule is missing to have it ready. The main issue that I am facing at the moment is a redirection issue, not sure how to split the traffic between the UI (opnform-client) and the API (opnform-api). I tried sending all the /api traffic to the opnform-api but still doesn't work. Of course I tried to translate what is in the [nginx.conf](https://github.com/JhumanJ/OpnForm/blob/main/docker/nginx.conf) file in this repo but didn't succeed yet. Maybe you can explain me how should be the redirection between these two docker containers and I can find a solution.

Looking forward to hearing from you.

```
map $original_uri $api_uri {
    ~^/api(/.*$) $1;
    default $original_uri;
}

server {
         listen       80;
         server_name  opnform;
         root         /app/public;

         access_log /dev/stdout;
         error_log  /dev/stderr error;

         index index.html index.htm index.php;

         location / {
           proxy_http_version 1.1;
           proxy_pass http://ui:3000;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-Port $server_port;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "Upgrade";
         }

         location ~/(api|open|local\/temp|forms\/assets)/ {
              set $original_uri $uri;
              try_files $uri $uri/ /index.php$is_args$args;
         }

         location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass api:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            #fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/$fastcgi_script_name;
            fastcgi_param SCRIPT_FILENAME /usr/share/nginx/html/public/index.php;
            fastcgi_param REQUEST_URI $api_uri;
         }
}
```

**Comment by JhumanJ** [comment]
- Root (/) traffic is proxied to the UI service (http://ui:3000).
- Traffic to specific paths (/api, /open, /local/temp, /forms/assets) involves some rewriting and is proxied to the API service (fastcgi_pass api:9000).

So I guess you need to somehow reproduce path-based routing in Kubernetes

**Comment by sergiotocalini** [comment]
What kind of rewriting is needed before proxying to the API service?

**Comment by JhumanJ** [comment]
```
map $original_uri $api_uri {
    ~^/api(/.*$) $1;
    default $original_uri;
}
```

This means if the URI starts with /api, it strips the /api prefix and uses the rest as $api_uri

**Comment by sergiotocalini** [comment]
This last part generates the issue of too many redirections and bad gateways. I hope the routing part can be improved in future releases. Happy to contribute to it if fits in the roadmap. I will try to make it work by having all the containers (nginx, opnform-api, onpform-client) running in a single pod. I will keep you posted over here and create a pull request to include the helm chart as soon as I make it work.
