### ISSUE TITLE
Feature Request: Matrix input row label text wrapping

### ISSUE THREAD

**Issue by asrulmunir** [JhumanJ/OpnForm#551]
Need text wrapping for text in matrix input row label so that user can see the complete label. On desktop we can hover mouse pointer over the text to see the complete label (still quite inconvenient). But on mobile, there is no way for user to see the complete label.

<img width="514" alt="Screenshot 2024-08-30 at 11 42 20 PM" src="https://github.com/user-attachments/assets/2306fcc1-7246-4b8d-b912-f02ceb3f0bc0">

Here is an example from Google Form:

<img width="633" alt="Screenshot 2024-08-30 at 11 48 35 PM" src="https://github.com/user-attachments/assets/7bd76bc0-8d18-4bd5-a4e6-0e9904c0fa2e">

**Comment by JhumanJ** [comment]
Thanks, fixed in https://github.com/JhumanJ/OpnForm/pull/556
