### ISSUE TITLE
[DEPLOYMENT] URLs are show localhost, not the var's from .env

### ISSUE THREAD

**Issue by pleibling** [JhumanJ/OpnForm#565]
**Describe the issue**
Hi,

i deploy with gitclone Docker Version, change .env and client/.env, then i start the container. I create an Form - in the overview and in the mails is localhost instead the url of the .env files. How can i change this?

**Deployment Environment**

-   OpnForm Version: latest
-   Hosting Platform: Docker self hosted
-   OS: Ubuntu 24.04.1

**Deployment Method**

-   [x] Docker 
-   [ ] Manual installation
-   [ ] Other (please specify)

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. gitclone
2. edit .env and client/.env
3. docker compose up -d

**Configuration Files**
.env:
APP_NAME="OpnForm"
APP_ENV=local
APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxx=
APP_DEBUG=false
APP_URL=https://forms.leibling.de

client/.env:
NUXT_LOG_LEVEL=
NUXT_PUBLIC_APP_URL=https://forms.leibling.de/
NUXT_PUBLIC_API_BASE=https://forms.leibling.de/api

**Comment by JhumanJ** [comment]
It seems like you don't have the latest version. Or you miss-placed the env file which moved to the `api` folder. Please use [our script](https://docs.opnform.com/deployment/docker#quick-start) to generate env files.

**Comment by JhumanJ** [comment]
Closing as it seems you made it work.

**Comment by hallerdavid** [comment]
i have the same error and just saw your comment @JhumanJ - i setup the server YESTERDAY and in the guide there was no hint for the API folder and there was no api folder created... is it since yesterday evening? :-D Because if not it looks like the guide showed false informations yesterday? i just test it with the new guide. Maybe this fix also #570 ! :-)

**Comment by hallerdavid** [comment]
Fixes also #570! thank you for your Work @JhumanJ

**Comment by JhumanJ** [comment]
Hey @hallerdavid not sure to understand - what was the issue? Anything we need to change in the docs?

**Comment by TimoReusch** [comment]
@JhumanJ Just stumbled across the same problem. Yes, the docs on this are outdated: https://docs.opnform.com/configuration/custom-domain

Since there are two `.env`, I think it would be good practice to refer to them as `api/.env` and `client/.env`.
