### ISSUE TITLE
Picture / Logo upload

### ISSUE THREAD

**Issue by hallerdavid** [JhumanJ/OpnForm#566]
Hello, i want to upload a logo / picture to my form. I click upload, get the dialogue and can choose a picture. But when i click upload nothing happens but popup is closed. :-) 

Can you give me a hint where i have to search? I used the docker-compose to deploy selfhosted.

**Comment by JhumanJ** [comment]
Please re-create this issue using the `Deployment/Self-hosted Issue` template and make sure to include logs specified in the template.
