### ISSUE TITLE
[DEPLOYMENT]  404 Page not found: /open/workspaces/

### ISSUE THREAD

**Issue by toxinliquid** [JhumanJ/OpnForm#586]
**Describe the issue**
A clear and concise description of the deployment or self-hosting issue you're experiencing.

**Deployment Environment**

-   OpnForm Version: latest
-   Hosting Platform: Self-hosted server]
-   OSUbuntu 20.04

**Deployment Method**

-   [ ] Docker
-   [x ] Manual installation
-   [ ] Other (please specify)

**Steps Taken**
Describe the steps you've taken to deploy the application:

1 cloned the repo
2 composer install in api folder
3 npm install nuxt and npm install in client
4  run the script
5 install mysql and migrate
6 npm build /npm run dev 

**Error Messages**
after running npm run dev when i try to login in i get 404 Page not found: /open/workspaces/
and 404 Page not found: /user

![aka](https://github.com/user-attachments/assets/75df0bb4-8f05-4472-afbf-14281c623382)

**Comment by JhumanJ** [comment]
Please Check the docs https://docs.opnform.com/deployment/local-deployment

**Comment by JhumanJ** [comment]
Please Check the docs you need env files https://docs.opnform.com/deployment/local-deployment

**Comment by toxinliquid** [comment]
environment files already created but the issue persists

**Comment by JhumanJ** [comment]
You need a web server for your back-end (ex: laravel Herd) and then you must provide the right value for the backend url to your front endLe 7 oct. 2024 à 10:08, toxinliquid ***@***.***> a écrit :﻿
environment files already created but the issue persists

**Comment by toxinliquid** [comment]
> You need a web server for your back-end (ex: laravel Herd) and then you must provide the right value for the backend url to your front endLe 7 oct. 2024 à 10:08, toxinliquid ***@***.***> a écrit :﻿ environment files already created but the issue persists —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

thanks working fine now
