### ISSUE TITLE
[DEPLOYMENT] invalid signature when I try open link to see attached file on form

### ISSUE THREAD

**Issue by Chugeno** [JhumanJ/OpnForm#604]
**Describe the issue**
I have managed to set up the email notification together with mailgun and everything is perfect. Except that when I click on the link in the email attachment that I get when I get a response from my form I get the message:

{
    ‘message": ’Invalid signature.’
}

Do you know what could be happening? from the dashboard of my OpnForm if the file opens correctly.

**Deployment Environment**

-   OpnForm Version: [last, i don't know how to know the version of opnform sorry]
-   Hosting Platform: [VPS on Oracle]
-   OS: [Ubuntu 22.04]

**Deployment Method**

-   [x] Docker
-   [ ] Manual installation
-   [ ] Other (please specify)

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. just follow the instructions
2. change mail configuration on the .env file in the root folder and fill and fill in the fields in the smtp configuration web interface. 
3. submission the form

**Error Messages**
{
    ‘message": ’Invalid signature.’
}

when click in the link on mail I receive

**Configuration Files** .env file on the root OpnForm folder

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=formulario@kusikay.com.ar
MAIL_PASSWORD=xxx
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=formulario@kusikay.com.ar
MAIL_FROM_NAME=Formulario Pedido

**Comment by Chugeno** [comment]
I just updated the docker image and now I don't get any mail when I fill the form to any address that I add in my smtp configuration interface. Neither to spam or anything.

I have seen that in the .env file inside the api there are also fields 

MAIL_MAILER=
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=

do i have to do anything with them?

**Comment by JhumanJ** [comment]
Hey can you please share one of these links (you can hide the domain ofc)

**Comment by Chugeno** [comment]
Hi! thanks for replying! I had a problem with my vps that I can't access it and it's offline. I'll fix that and get back to you. Sorry...

**Comment by Chugeno** [comment]
Hi! thanks for replying! I had a problem with my vps that I can't access it and it's offline. I'll fix that and get back to you. Sorry...
