### ISSUE TITLE
[Customise Landing Page and Pdf] 

### ISSUE THREAD

**Issue by FigJam23** [JhumanJ/OpnForm#607]
** is there a way to chsngne the default landing Page / home page?  And is it possible to Printing or saving to PDF in admin  for later viewing of the actual filled form I only see option to export to a csv format .**

**Docker on Debian 12**

-   OpnForm Version: [unsure how to check version just pulled yesstersay from recomended docker istall script]
-   Hosting Platform:  Self-hosted server]
-   OS: [Debian 12]

**Deployment Method**

-   [x] Docker
-   [x] Manual installation
-   [x] Other (please specify)

**Steps Taken**
Describe the steps you've taken to deploy the application:

1. Installed Debian 12 on proxmox CT
2. RUN install scripts for docker
3. Changed admin login details

**Error Messages**
None that I know of

**Configuration Files**
Default configuration files

**Logs**
Unsure where to find logs still working that out

So I would like to change the default landing page like backgrounds and styling couldn't workout what .vue file to edit. I'm also trying to workout how I can  also have the ability to view the filled form after submission not just export to csv file maybe include a pdf or printable file after a submitted form has been made.

This project looks realy good and almost meets my needs. Thanks for the team and work put into this form builder realy cool love it. Any help would be much appreciated

**Comment by FigJam23** [comment]
I have kinda got some kinda pdf export code working via the code block but it's nit ideal and would love to have this saved to admin automatically when submitting a form. Also still need to know how to edit home / Landing Page.

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Export Full Page to PDF</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
  <style>
    /* Style adjustments for print and PDF export */
    .form-label {
      margin-bottom: 5px; /* Add space between label and field */
    }
    .form-field {
      display: block;
      margin-top: 10px; /* Space above each field */
    }
    @media print {
      button {
        display: none; /* Hide buttons in print preview */
      }
    }
  </style>
</head>
<body>

  <!-- Your page content with form fields -->
  <h1>Your Form Title</h1>
  <label class="form-label">Field Label 1</label>
  <input class="form-field" type="text">
  
  <label class="form-label">Field Label 2</label>
  <input class="form-field" type="text">
  
  <!-- More content as needed -->

  <!-- Export to PDF Button -->
  <button onclick="exportFullPageToPDF()">Export Full Page to PDF</button>

  <!-- All-in-one script for full page PDF export with layout adjustments -->
  <script>
    async function exportFullPageToPDF() {
      const { jsPDF } = window.jspdf;
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      // Hide all buttons temporarily
      document.querySelectorAll('button').forEach(button => button.style.display = 'none');
      
      // Capture the full page with updated layout
      await html2canvas(document.body, {
        scale: 2,
        scrollY: 0,
      }).then((canvas) => {
        const imgData = canvas.toDataURL('image/jpeg', 1.0);
        
        // Calculate the number of PDF pages needed
        const pageHeight = pdf.internal.pageSize.getHeight();
        const imgHeight = (canvas.height * 210) / canvas.width;
        
        let position = 0;
        
        pdf.addImage(imgData, 'JPEG', 0, position, 210, imgHeight);
        
        // Add more pages if content exceeds one page
        while (position + imgHeight > pageHeight) {
          position -= pageHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'JPEG', 0, position, 210, imgHeight);
        }
        
        pdf.save('FullPageExport.pdf');
      });

      // Show buttons again after PDF generation
      document.querySelectorAll('button').forEach(button => button.style.display = 'block');
    }
  </script>

</body>
</html>
```

**Comment by FigJam23** [comment]
ok, I've managed to get PDF creation and upload working and viewable in admin form submissions by using a workaround using a file upload block and a code upload block below so far, it's working well. I'll share my code for the code block in case others want to try it out and maybe refine it more

``` <!-- HTML Button to trigger PDF capture and upload -->
<button onclick="captureAndUploadPDF()">Capture Page as PDF and Upload</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>

<script>
  async function captureAndUploadPDF() {
    const { jsPDF } = window.jspdf;
    const pdf = new jsPDF('p', 'mm', 'a4');

    // Ignore tainted elements and cross-origin restrictions
    await html2canvas(document.body, { scale: 2, allowTaint: true }).then((canvas) => {
      const imgData = canvas.toDataURL('image/jpeg', 1.0);
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgHeight = (canvas.height * 210) / canvas.width;
      let position = 0;

      pdf.addImage(imgData, 'JPEG', 0, position, 210, imgHeight);
      while (position + imgHeight > pageHeight) {
        position -= pageHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'JPEG', 0, position, 210, imgHeight);
      }
    });

    // Convert PDF to Blob
    const pdfBlob = pdf.output('blob');

    // Locate the hidden file input dynamically
    const fileInput = Array.from(document.querySelectorAll('input[type="file"]')).find(input => input.classList.contains('hidden'));

    if (!fileInput) {
      alert("Upload area not found. Please check the form setup.");
      return;
    }

    // Temporarily show the hidden input
    fileInput.style.display = 'block';

    // Create a new File object to attach to the file input
    const pdfFile = new File([pdfBlob], "PageCapture.pdf", { type: "application/pdf" });
    const dataTransfer = new DataTransfer();
    dataTransfer.items.add(pdfFile);
    fileInput.files = dataTransfer.files;

    // Trigger a change event to simulate the file being added manually
    const event = new Event("change");
    fileInput.dispatchEvent(event);

    // Hide the input again
    fileInput.style.display = 'none';

    alert("PDF added to upload area successfully!");
  }
</script>
```

I still haven't worked out how to change the landing / Home Page but am working on that next anyone else can help with that please do

**Comment by JhumanJ** [comment]
Hey - love the pdf trick. We'll start working on this as a native feature pretty soon.
About the landing page, do you mean being able to redirect the root path to another page? Can you please share more about the use case?

**Comment by FigJam23** [comment]
> Hey - love the pdf trick. We'll start working on this as a native feature pretty soon. About the landing page, do you mean being able to redirect the root path to another page? Can you please share more about the use case?

It took me a bit to get this to work, hidding the file upload block still dosnt work ATM but if it's visible it does. Definitely looking forward to the feature being included. I'll attach a image of the default landing page.
![Screenshot_20241103_223551_Chrome](https://github.com/user-attachments/assets/7b9f13be-8c08-4d4e-96b6-769bf94cd29f)

**Comment by JhumanJ** [comment]
What would you expect from this landing page? Something more neutral? Or more customization?

**Comment by FigJam23** [comment]
> What would you expect from this landing page? Something more neutral? Or more customization?

I'd like to customize it if possible, even the loging in page to would be good, to customize.  I've tried editing the .vue files but no luck and unsure what ones to edit.

**Comment by FigJam23** [comment]
I managed to make some changes to the .vue files for landing and home pages  so far think I'm on the right track, no errors and everything still works. I'll share the process when I have tested more. But definitely looks promising since there not alot of support yet on this project, I'm pick that will change as time goes on. It would be nice to have the ability to do this from the UI in the future.
