### ISSUE TITLE
[DEPLOYMENT] Cannot switch language of form

### ISSUE THREAD

**Issue by stavismed** [JhumanJ/OpnForm#612]
When opening the settings / general of a form, there is no language chooser (as described in the help https://help.openforms.com/Customize/Change-the-language-of-your-form)

This is also on opnform.com

**Deployment Environment**

-   OpnForm Version: 1.4.1
-   Hosting Platform: Self-hosted server
-   OS: Ubuntu 22.04 WSL2

**Deployment Method**

-   [ ] Docker

**Steps Taken**
Just created a form and looked in the general-settings of it

**Error Messages**
There is no language-chooser
I think I missed something fundamental, but cannot find any hints so maybe someone can point me to something obvious ;-)

**Comment by JhumanJ** [comment]
Hi, we don't have a language translation feature. This page is not for opnform.com, but for some other software.

**Comment by stavismed** [comment]
Sorry - 🤦‍♂️ openforms != opnform
my bad.
I wished so much for this feature, I didn't even recognize I was on the wrong path.

This would really be a great feature!
