### ISSUE TITLE
[BUG] Logic Mal Function

### ISSUE THREAD

**Issue by tomcatcw1980** [JhumanJ/OpnForm#624]
**Describe the bug**
I have the following problem: I have a multi-section input in my form. The following inputs are possible:

Option A Send print catalogue
Option B xyz
Option C xyz
Option D xyz

As soon as option A, send print catalogue is selected, the input fields street, house number, postcode, city and country should be displayed and filled in as mandatory fields. If option A is not selected, the above address fields should not be displayed and should not have to be filled in.

The display depends on the selection of option A, i.e. the fields are generally not displayed and appear when option A is selected. This works. 

The error is now as follows: If you do not select option A, but one or more of the other three options, an error is still displayed when the form is sent, stating that the address fields must be filled in. 

**To Reproduce**
See Screenshots how the logic is configured.

**Expected behavior**
I would expect that the error for filling in the address data is only displayed if option A (send print catalogue) has been selected in the multi-option input. As soon as only one or three of the other options are selected, it should be hidden (works), but only optionally.

**Screenshots**

Displayed error:

![Screenshot 2024-11-21 121259](https://github.com/user-attachments/assets/53ef6143-8054-43d9-a588-1a4a7b4f5273)

Configured logic:

![Screenshot 2024-11-21 121411](https://github.com/user-attachments/assets/fdbbfabc-4164-42d4-bcb8-fe4e4b911852)

**Environment (please complete the following information):**

-   Envionement: Docker
-   Browser: Chrome, but always tested in Edge and Firefox with same behaviour
-   OpnForm Version: latest

**Comment by JhumanJ** [comment]
Should be fixed!
