### ISSUE TITLE
[BUG] Confirmation Mails not sent

### ISSUE THREAD

**Issue by tomcatcw1980** [JhumanJ/OpnForm#638]
**Describe the bug**
I have successfully set up Opnform via Docker. I have stored all the important variables in the api/.env file, including for sending mail via a separate mail server.

In a form, which works well in itself, I have stored an e-mail notification under Integrations. Unfortunately, no mail is sent. I also do not see any log entry in my e-mail server that any connection has been established by Opnform. Under Past Events there is also no entry about the dispatch.

Translated with DeepL.com (free version)

**To Reproduce**

**Expected behavior**
Successfully send mails.

**Screenshots**

**Environment (please complete the following information):**

-   Envionement [Cloud, Docker, Self-hosted, etc.]
-   Browser [e.g. chrome, safari]
-   OpnForm Version [e.g. 22]

**Additional context**

**Comment by JhumanJ** [comment]
Hi, can you please share your back-end .env file (hiding secrets of cours). Anything in the logs (check laravel.log)? It seems to be a configuration issue.

**Comment by JhumanJ** [comment]
Email setup guide: https://docs.opnform.com/configuration/email-setup

**Comment by tomcatcw1980** [comment]
Hi, 

thank you for your reply. I used to above mentioned guide.

Here is an extract of the api/.env file

`APP_NAME="OpnForm"
APP_ENV=local
APP_KEY=base64:***secret***
APP_DEBUG=true
APP_URL=https://opnform.foo.bar

SELF_HOSTED=true

LOG_CHANNEL=errorlog
LOG_LEVEL=debug

FILESYSTEM_DRIVER=local

BROADCAST_CONNECTION=log

CACHE_STORE=redis
CACHE_DRIVER=redis

QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120

MAIL_MAILER=smtp
MAIL_HOST=mail.foo.bar
MAIL_PORT=587
MAIL_USERNAME=***secret***
MAIL_PASSWORD=***secret***
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=***secret***
MAIL_FROM_NAME=OpnForm

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

JWT_TTL=1440
JWT_SECRET=***secret***

MUX_WORKSPACE_ID=
MUX_API_TOKEN=

OPEN_AI_API_KEY=
FRONT_API_SECRET=***secret***

H_CAPTCHA_SITE_KEY=***secret***
H_CAPTCHA_SECRET_KEY=***secret***
`

I saw that there are tweo .env files in the folder api: .env and .env.docker I only filled the .env file.

**Comment by JhumanJ** [comment]
Yes you need to fill the .env file. Did you restart the containers after changing the file? Any things from the logs?

**Comment by tomcatcw1980** [comment]
Yes, I restarted the container with docker compose up -d --force-recrecreate, as I always do.

Where can I find the logs?

**Comment by tomcatcw1980** [comment]
There is no laravel.log in that folder. How to activate?

**Comment by tomcatcw1980** [comment]
When I switch to My Account > Workplace Settings and Invite a new user, this notifitcation mail is successfully sent.

**Comment by tomcatcw1980** [comment]
No clue what the problem is, but I just designed a new form and now the notifications are being sent.

**Comment by JhumanJ** [comment]
Not sure what happened, closing this for now!
