### ISSUE TITLE
[Feature Request] Hide field name on desktop

### ISSUE THREAD

**Issue by JonBons** [JhumanJ/OpnForm#642]
Currently we have the ability to hide field names but this hides them on both desktop and mobile sizes, if there was an alternative "Hide field name on desktop" switch that handles visibility with window size I'd be able to better support some form scenarios.

In my case since I can't build out a real table with textbox input I'm using the field widths and hide field name feature to emulate one but this falls flat when you start hiding field names as it becomes unusable on mobile.

Desktop & form setup:
![firefox_cVqG2Uml8L](https://github.com/user-attachments/assets/7e2978a2-87b6-426e-bf3d-025036638c74)
Mobile:
![firefox_yqfjkqYE8o](https://github.com/user-attachments/assets/1ea8c8d1-59b3-4458-ad6d-f50f0961156c)

**Comment by JhumanJ** [comment]
Hey although I understand what you're trying to achieve, we won't implement something for this as it's too specific. However you can add some custom CSS code with media queries to achieve this!
