### ISSUE TITLE
[Feature Request] Add calculated fields to sum up values

### ISSUE THREAD

**Issue by changchichung** [JhumanJ/OpnForm#649]
We have some forms and we want to automatically calculate the sum of certain fields  then show the sum value in the submisson page/ notification email when the user submits the form.

I don't see any "value" in any fields. maybe it's not ready to do so now ?
would you please consider to add this feature ?

**Comment by JhumanJ** [comment]
Hey this is planned, but not possible yet. Feature request here: https://feedback.opnform.com/p/computed-fields
