### ISSUE TITLE
Hidden field data not pushed to Slack and Integrations webhook

### ISSUE THREAD

**Issue by mhphilip** [JhumanJ/OpnForm#66]
Hi,

I've added a hidden field in one of my forms. When using a Slack or custom (webhook) integration the hidden fields are not being pushed. I do see the content of the field in the Submissions overview. 

For the CSV export the hidden fields do appear as labels, but are left empty.

It's quite common to e.g. use a hidden (dynamic) field that you can pre-fill using a URL parameter. That already works. It is quite necessary to then also be able to send that data to an external endpoint so you can find the reference to that field from the form's data.

It would be great if you could implement this.

**Comment by mhphilip** [comment]
Found out this is quite easy:

PostFormDataToWebhook.php:58

$formatter = (new FormSubmissionFormatter($event->form, $event->data))->**showHiddenFields()**;

**Comment by JhumanJ** [comment]
Hey Philip, thanks for the heads up. I've made the change, and I'm about to deploy on [OpnForm.com](OpnForm.com) 👍 
Commit: https://github.com/JhumanJ/OpnForm/commit/977cd1647aa4e488b0e663db91cc6bb5593e5858

**Comment by mhphilip** [comment]
That was quick. Thank you
