### ISSUE TITLE
Feature request: calling a webhooks from within a form and populating form fields using an API's result

### ISSUE THREAD

**Issue by mhphilip** [JhumanJ/OpnForm#68]
This one is a little bit more complex but might offer a lot of extra usability. 

It would be nice if it would be possible to call an external webhook from within a form. E.g. a web service (API) that gets the address (streetname and city) based on a zipcode and address number (very common in the Netherlands where I live). Or a web service that checks some client-specific logic based on one of the fields in the form, an example being "checking whether someone's "city" is within the list of cities a client offers their services to. Since you don't know what kind of API's one would like to call, a generic mechanism would suffice.

To implement this, you would have to be able to configure a webhook URL on a field level, which then gets POST-ed the entire payload of the form (thus far). This could trigger by using a button or by leaving the field in the UI. 

The web hook would then need to return some specific payload back, which OpnForm could use to populate (other) fields in the form. One could use Zapier or Make.com (formerly Integromat) or a similar service or code something themselves to do the translations to the required specific format.

Let me know if this makes any sense, if not I'll elaborate.

**Comment by JhumanJ** [comment]
Hey Philip, thanks again for all of your great feedback. Although we could accept a PR implementing this, we will not be working on this. This is complex, specific, and it requires advanced tech knowledge, for now we prefer to focus and more accessible features, providing value to a wider audience.
