### ISSUE TITLE
Unable to edit the select field type 

### ISSUE THREAD

**Issue by ifly-leonard** [JhumanJ/OpnForm#72]
Hellu! 
First of all. Love the app. You deserve the best things in the world for doing this.

I have a form setup on your cloud and I run into an issue whenever I try to change the field type. This unfortunately stops me from saving the form later on. 

### Steps to reproduce the issue
- Create a form 
- Add a select field type 
- Save the form 
- Re-open the form edit page 
- Open the settings modal of the field, and on the header, press the "change field type" button. 
- Observe error on the console. 

Something is breaking in the Vue side of things. 

I also have a suggestion, can we have a try case for all the functions that attempt to change the fields or for whatever operations so that if and when something goes wrong, it won't mess with saving the form. I felt dejected when I created a detailed form for 30 minutes and I figured out that I won't be able to save the form and have to do it all again from scratch.

**Comment by JhumanJ** [comment]
Hey @ifly-leonard , thanks a lot for your feedback. We've fixed the issue in https://github.com/JhumanJ/OpnForm/pull/74 🙌
I'm sorry you lost some time. Ideally, we'd like to keep changes history in the browser to prevent this (and other potential bugs) from messing with your work.
