### ISSUE TITLE
Error on the managed app while attempting to switch tabs

### ISSUE THREAD

**Issue by ifly-leonard** [JhumanJ/OpnForm#80]
```TypeError: Failed to fetch dynamically imported module: https://d3ietpyl4f2d18.cloudfront.net/45099d96-8631-4a3f-b66b-7913d799f0b7/build/assets/analytics-827ed066.js```

Steps to reproduce: 
- Go to a saved form 
- Switch to the "analytics" tab
- Observe error on the console

**Comment by JhumanJ** [comment]
Hey @ifly-leonard, I belive recent changes fixed this. Could you please confirm that it's ok on your side?
