### ISSUE TITLE
Feature Request: Add discord webhook integration

### ISSUE THREAD

**Issue by ifly-leonard** [JhumanJ/OpnForm#81]
This is a fairly simple feature to add since the form already has webhooks in place. The user needs to add a discord webhook URL, and once the URL is added, the app needs to send a test payload to verify if it works (like how Github does). For now, a notification for every new form submission would do.

**Comment by JhumanJ** [comment]
We already have a Slack integration, so this is similar. Anyone willing to contribute to this is welcome 🙏

**Comment by ifly-leonard** [comment]
I can try giving it a crack! Let's see @JhumanJ

**Comment by JhumanJ** [comment]
Awesome! Let me know if you have any question or need any help!

**Comment by ifly-leonard** [comment]
Okay, I've never worked with vue store before, but somehow figured out what's what under the hood and made some progress. 

Planning to add a config file for 
- Message content (where users can configure if they want to trigger @here / @everyone or a role etc) 
- Add statistics to the form

![image](https://user-images.githubusercontent.com/29737466/215275469-92a63fc4-7cf1-4ee6-b2fc-2a0dffc9a476.png)

**Comment by ifly-leonard** [comment]
Opened a PR #83 for this @JhumanJ @chiragnotionforms. Hope this gets merged 🥳

**Comment by JhumanJ** [comment]
Thanks! Will review the PR soon 🚀
