### ISSUE TITLE
Unable to disable Slack & Discord notifications

### ISSUE THREAD

**Issue by ifly-leonard** [JhumanJ/OpnForm#84]
Once a slack or discord URL is added, I cannot delete/disable it. When you click the toggle, it hides the input field where you enter the webhook URL, but when you hit "Save Form" and reload the page, you will see that the notifications are still enabled. 

Steps to reproduce: 
1. Open a form 
2. Enable notifications (Discord / Slack) 
3. Save the form 
4. Reopen the form. (The expected behavior is to have the notifications disabled)
5. Observe the notifications still enabled. 

P.S I tried to do this as well in my PR, but not too well-versed with Vue. Perhaps this can be controlled via the form validation rule?

**Comment by JhumanJ** [comment]
Thanks for the report. Don't worry if you're not familiar with Vue we can take care of it on Monday.

**Comment by JhumanJ** [comment]
Hey @ifly-leonard, I belive recent changes fixed this. Could you please confirm that it's ok on your side?
