### ISSUE TITLE
How to  integrate opnForm into our custom Vue3 application?

### ISSUE THREAD

**Issue by krupa5** [JhumanJ/OpnForm#85]
Hi,

We are trying to integrate opnForm into our custom Vue3 application. Kindly provide guidance on the steps necessary for integrating the form code into our vue3 setup in a thorough and efficient manner. This will help us a lot to get started. As a standalone, we have already executed and it seems to be working fine, just need to integrate within our project.

**Comment by JhumanJ** [comment]
Hey, this is not a package but a standalone project. You can embed forms in your applications (via iframe), but we don't provide guidance on integrating this in another codebase. Moreover we're using Vue2, so that might make the task even harder.
